[package]
name = "solidity_v2_testing_solc"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
Inflector = { workspace = true }
infra_utils = { workspace = true }
rayon = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slang_solidity_v2 = { workspace = true }
slang_solidity_v2_common = { workspace = true }
solidity_testing_utils = { workspace = true }
solidity_v2_testing_utils = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
