# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "PragmaDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "PragmaKeyword"
          - choice:
              - reference: "ABICoderPragma"
              - reference: "ExperimentalPragma"
              - reference: "VersionPragma"
      terminator:
        reference: "Semicolon"

- name: "ABICoderPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AbicoderKeyword"
      - reference: "Identifier"

- name: "ExperimentalPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ExperimentalKeyword"
      - choice:
          # Grammar says any token but semicolon
          - reference: "AsciiStringLiteral"
          - reference: "Identifier"

- name: "VersionPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "SolidityKeyword"
      - reference: "VersionPragmaExpressions"

- name: "VersionPragmaExpressions"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "VersionPragmaExpression"

- name: "VersionPragmaExpression"
  kind: "PrecedenceParser"
  unversioned:
    operatorExpressions:
      - name: "VersionPragmaBinaryExpression"
        model: "BinaryLeftAssociative"
        operator:
          reference: "VersionPragmaOrOperator"

      - name: "VersionPragmaBinaryExpression"
        model: "BinaryLeftAssociative"
        operator:
          reference: "VersionPragmaRangeOperator"

      - name: "VersionPragmaUnaryExpression"
        model: "UnaryPrefix"
        operator:
          reference: "VersionPragmaUnaryOperator"

    primaryExpression:
      reference: "VersionPragmaSpecifier"

- name: "VersionPragmaOrOperator"
  kind: "Parser"
  inlined: true
  unversioned:
    reference: "BarBar"

- name: "VersionPragmaRangeOperator"
  kind: "Parser"
  inlined: true
  unversioned:
    reference: "Minus"

- name: "VersionPragmaUnaryOperator"
  kind: "Parser"
  inlined: true
  unversioned:
    choice:
      - reference: "Caret"
      - reference: "Tilde"
      - reference: "Equal"
      - reference: "LessThan"
      - reference: "GreaterThan"
      - reference: "LessThanEqual"
      - reference: "GreaterThanEqual"

- name: "VersionPragmaSpecifier"
  kind: "Parser"
  unversioned:
    separatedBy:
      parser:
        reference: "VersionPragmaValue"
      separator:
        reference: "Period"

- name: "VersionPragmaValue"
  kind: "Scanner"
  unversioned:
    oneOrMore:
      choice:
        - range:
            from: "0"
            to: "9"
        - terminal: "x"
        - terminal: "X"
        - terminal: "*"
