# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "TypeName"
  kind: "PrecedenceParser"
  unversioned:
    operators:
      - name: "ArrayTypeName"
        model: "UnaryPostfix"
        delimitedBy:
          open:
            reference: "OpenBracket"
          expression:
            optional:
              reference: "Expression"
          close:
            reference: "CloseBracket"

    primaryExpression:
      choice:
        - reference: "FunctionType"
        - reference: "MappingType"
        - reference: "ElementaryType"
        - reference: "IdentifierPath"
