name: "cooldown-check"

runs:
  using: "composite"
  steps:
    - name: "Cache cooldown data"
      uses: "actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830" # v4.3.0
      with:
        path: "**/target/slang-cache/cargo-cooldown-check"
        key: "cooldown-check-v1-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"
        restore-keys: |
          cooldown-check-v1-${{ runner.os }}-

    - name: "Cargo cooldown check"
      run: "./scripts/bin/with-hermit cargo cooldown-check"
      shell: "bash"
