[package]
name = "codegen_testing"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
codegen_schema = { workspace = true }
codegen_utils = { workspace = true }
walkdir = { workspace = true }
