[package]
name = "codegen_language_definition"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
codegen_language_internal_macros = { workspace = true }
indexmap = { workspace = true }
Inflector = { workspace = true }
infra_utils = { workspace = true }
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
strum_macros = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
