# Please see the documentation for all configuration options:
#
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[cargo] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[npm] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      # openzeppelin contracts used in perf tests. don't update/change, to prevent variations/failures in results:
      - dependency-name: "@openzeppelin/contracts"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[github-actions] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[pip] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"
