# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "LeadingTrivia"
  kind: "TriviaParser"
  unversioned:
    oneOrMore:
      choice:
        - reference: "Whitespace"
        - reference: "EndOfLine"
        - reference: "MultilineComment"
        - reference: "SingleLineComment"

- name: "TrailingTrivia"
  kind: "TriviaParser"
  unversioned:
    sequence:
      - zeroOrMore:
          choice:
            - reference: "Whitespace"
            - reference: "SingleLineComment"
      - reference: "EndOfLine"

- name: "EndOfFileTrivia"
  kind: "TriviaParser"
  unversioned:
    oneOrMore:
      choice:
        - reference: "Whitespace"
        - reference: "EndOfLine"
        - reference: "MultilineComment"
        - reference: "SingleLineComment"

- name: "Whitespace"
  kind: "Scanner"
  unversioned:
    oneOrMore:
      choice:
        - terminal: " "
        - terminal: "\t"

- name: "EndOfLine"
  kind: "Scanner"
  unversioned:
    oneOrMore:
      choice:
        - terminal: "\r"
        - terminal: "\n"

- name: "MultilineComment"
  kind: "Scanner"
  unversioned:
    delimitedBy:
      open: "/*"
      expression:
        zeroOrMore:
          choice:
            - not:
                terminal: "*"
            - sequence:
                - terminal: "*"
                - not:
                    terminal: "/"
      close: "*/"

- name: "SingleLineComment"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "//"
      - zeroOrMore:
          not:
            choice:
              - terminal: "\r"
              - terminal: "\n"
