# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "StateVariableDeclaration"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "TypeName"
          - zeroOrMore:
              reference: "StateVariableAttribute"
          - reference: "Identifier"
          - optional:
              sequence:
                - reference: "Equal"
                - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "StateVariableAttribute"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "OverrideSpecifier"
      - reference: "ConstantKeyword"
      - reference: "ImmutableKeyword"
      - reference: "InternalKeyword"
      - reference: "PrivateKeyword"
      - reference: "PublicKeyword"
