# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "StateVariableDeclaration"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "TypeName"
      - zeroOrMore:
          reference: "StateVariableAttribute"
      - reference: "Identifier"
      - optional:
          sequence:
            - terminal: "="
            - reference: "Expression"
      - terminal: ";"

- name: "StateVariableAttribute"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "OverrideSpecifier"
      - reference: "ConstantKeyword"
      - reference: "ImmutableKeyword"
      - reference: "InternalKeyword"
      - reference: "PrivateKeyword"
      - reference: "PublicKeyword"
