# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "IfStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IfKeyword"
      - delimitedBy:
          open:
            reference: "OpenParen"
          parser:
            reference: "Expression"
          close:
            reference: "CloseParen"
      - reference: "Statement"
      - optional:
          sequence:
            - reference: "ElseKeyword"
            - reference: "Statement"

- name: "ForStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ForKeyword"
      - delimitedBy:
          open:
            reference: "OpenParen"
          parser:
            sequence:
              - choice:
                  - reference: "SimpleStatement"
                  - reference: "Semicolon"
              - choice:
                  - reference: "ExpressionStatement"
                  - reference: "Semicolon"
              - optional:
                  reference: "Expression"
          close:
            reference: "CloseParen"
      - reference: "Statement"

- name: "WhileStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "WhileKeyword"
      - delimitedBy:
          open:
            reference: "OpenParen"
          parser:
            reference: "Expression"
          close:
            reference: "CloseParen"
      - reference: "Statement"

- name: "DoWhileStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "DoKeyword"
          - reference: "Statement"
          - reference: "WhileKeyword"
          - delimitedBy:
              open:
                reference: "OpenParen"
              parser:
                reference: "Expression"
              close:
                reference: "CloseParen"
      terminator:
        reference: "Semicolon"

- name: "ContinueStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        reference: "ContinueKeyword"
      terminator:
        reference: "Semicolon"

- name: "BreakStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        reference: "BreakKeyword"
      terminator:
        reference: "Semicolon"

- name: "ReturnStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "ReturnKeyword"
          - optional:
              reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "EmitStatement"
  kind: "Parser"
  versioned:
    0.4.21:
      terminatedBy:
        parser:
          sequence:
            - reference: "EmitKeyword"
            - reference: "IdentifierPath"
            - reference: "ArgumentsDeclaration"
        terminator:
          reference: "Semicolon"

- name: "DeleteStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "DeleteKeyword"
          - reference: "Expression"
      terminator:
        reference: "Semicolon"
