[package]
name = "codegen_v2_runner"
description = "Generates the artifacts required to use slang v2."
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
codegen_v2_generator = { workspace = true }
infra_utils = { workspace = true }
solidity_v2_language = { workspace = true }
tera = { workspace = true }

[lints]
workspace = true
