# rustfmt nightly configuration options:
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

group_imports = "StdExternalCrate"
imports_granularity = "Module"
match_arm_leading_pipes = "Always"
