#
# rustfmt nightly configuration options:
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
#

array_width = 60
attr_fn_like_width = 70
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 60
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
# disable_all_formatting (because why?)
doc_comment_code_block_width = 100
# edition (we set the edition through the workspace root 'Cargo.toml')
# emit_mode (internal option in 'rustfmt')
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
# fn_args_layout (option is deprecated, use 'fn_params_layout' instead)
fn_call_width = 60
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = false
format_strings = false
group_imports = "Preserve"
hard_tabs = false
hex_literal_case = "Preserve"
hide_parse_errors = false
ignore = []
imports_granularity = "Preserve"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
# make_backup (internal option in 'rustfmt')
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 100
merge_derives = true
# merge_imports (option is deprecated, use 'imports_granularity' instead)
newline_style = "Auto"
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = false
# print_misformatted_file_names (internal option in 'rustfmt')
remove_nested_parens = true
reorder_impl_items = false
reorder_imports = true
reorder_modules = true
# required_version (we set the version through rustup)
short_array_element_width_threshold = 10
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
skip_children = false
skip_macro_invocations = []
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
version = "One"
where_single_line = false
wrap_comments = false
