# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "YulBlock"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBrace"
      expression:
        optional:
          reference: "YulStatementsList"
      close:
        reference: "CloseBrace"

- name: "YulStatementsList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "YulStatement"

- name: "YulStatement"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "YulBlock"
        - reference: "YulFunctionDefinition"
        - reference: "YulDeclarationStatement"
        - reference: "YulAssignmentStatement"
        - reference: "YulIfStatement"
        - reference: "YulForStatement"
        - reference: "YulSwitchStatement"
        - reference: "YulBreakStatement"
        - reference: "YulContinueStatement"
        - reference: "YulExpression"
    0.6.0:
      # added "YulLeaveStatement"
      choice:
        - reference: "YulBlock"
        - reference: "YulFunctionDefinition"
        - reference: "YulDeclarationStatement"
        - reference: "YulAssignmentStatement"
        - reference: "YulIfStatement"
        - reference: "YulForStatement"
        - reference: "YulSwitchStatement"
        - reference: "YulLeaveStatement"
        - reference: "YulBreakStatement"
        - reference: "YulContinueStatement"
        - reference: "YulExpression"

- name: "YulDeclarationStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "LetKeyword"
      - reference: "YulIdentifierPathsList"
      - optional:
          sequence:
            - reference: "ColonEqual"
            - reference: "YulExpression"

- name: "YulFunctionDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "FunctionKeyword"
      - reference: "YulIdentifier"
      - reference: "YulParametersDeclaration"
      - optional:
          reference: "YulReturnsDeclaration"
      - reference: "YulBlock"

- name: "YulParametersDeclaration"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      expression:
        optional:
          reference: "YulIdentifiersList"
      close:
        reference: "CloseParen"

- name: "YulReturnsDeclaration"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "MinusGreaterThan"
      - reference: "YulIdentifiersList"

- name: "YulAssignmentStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "YulIdentifierPathsList"
      - reference: "ColonEqual"
      - reference: "YulExpression"

- name: "YulIfStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IfKeyword"
      - reference: "YulExpression"
      - reference: "YulBlock"

- name: "YulLeaveStatement"
  kind: "Parser"
  versioned:
    0.6.0:
      reference: "LeaveKeyword"

- name: "YulBreakStatement"
  kind: "Parser"
  unversioned:
    reference: "BreakKeyword"

- name: "YulContinueStatement"
  kind: "Parser"
  unversioned:
    reference: "ContinueKeyword"

- name: "YulForStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ForKeyword"
      - reference: "YulBlock"
      - reference: "YulExpression"
      - reference: "YulBlock"
      - reference: "YulBlock"

- name: "YulSwitchStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "SwitchKeyword"
      - reference: "YulExpression"
      - reference: "YulSwitchCasesList"

- name: "YulSwitchCasesList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "YulSwitchCase"

- name: "YulSwitchCase"
  kind: "Parser"
  unversioned:
    sequence:
      - choice:
          - reference: "DefaultKeyword"
          - sequence:
              - reference: "CaseKeyword"
              - reference: "YulLiteral"
      - reference: "YulBlock"
