- name: "AbicoderKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "abicoder"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "AbstractKeyword"
  kind: "Scanner"
  versioned:
    0.6.0:
      trailingContext:
        scanner:
          terminal: "abstract"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "AddressKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "address"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "AnonymousKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "anonymous"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "AsKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "as"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "AssemblyKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "assembly"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "BoolKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "bool"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "BreakKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "break"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ByteKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      trailingContext:
        scanner:
          terminal: "byte"
        notFollowedBy:
          reference: "IdentifierPart"
    0.8.0: null

- name: "CalldataKeyword"
  kind: "Scanner"
  versioned:
    0.5.0:
      trailingContext:
        scanner:
          terminal: "calldata"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "CaseKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "case"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "CatchKeyword"
  kind: "Scanner"
  versioned:
    0.6.0:
      trailingContext:
        scanner:
          terminal: "catch"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "ConstantKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "constant"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ConstructorKeyword"
  kind: "Scanner"
  versioned:
    0.4.22:
      trailingContext:
        scanner:
          terminal: "constructor"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "ContinueKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "continue"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ContractKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "contract"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "DaysKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "days"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "DefaultKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "default"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "DeleteKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "delete"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "DoKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "do"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ElseKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "else"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "EmitKeyword"
  kind: "Scanner"
  versioned:
    0.4.21:
      trailingContext:
        scanner:
          terminal: "emit"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "EnumKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "enum"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ErrorKeyword"
  kind: "Scanner"
  versioned:
    0.8.4:
      trailingContext:
        scanner:
          terminal: "error"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "EtherKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "ether"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "EventKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "event"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ExperimentalKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "experimental"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ExternalKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "external"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FallbackKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "fallback"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FalseKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "false"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FinneyKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      trailingContext:
        scanner:
          terminal: "finney"
        notFollowedBy:
          reference: "IdentifierPart"
    0.7.0: null

- name: "ForKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "for"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FromKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "from"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FunctionKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "function"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "GlobalKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "global"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "GweiKeyword"
  kind: "Scanner"
  versioned:
    0.6.11:
      trailingContext:
        scanner:
          terminal: "gwei"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "HoursKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "hours"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "IfKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "if"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ImmutableKeyword"
  kind: "Scanner"
  versioned:
    0.6.5:
      trailingContext:
        scanner:
          terminal: "immutable"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "ImportKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "import"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "IndexedKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "indexed"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "InterfaceKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "interface"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "InternalKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "internal"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "IsKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "is"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "LeaveKeyword"
  kind: "Scanner"
  versioned:
    0.6.0:
      trailingContext:
        scanner:
          terminal: "leave"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "LetKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "let"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "LibraryKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "library"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "MappingKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "mapping"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "MemoryKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "memory"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "MinutesKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "minutes"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ModifierKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "modifier"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "NewKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "new"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "OverrideKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "override"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "PayableKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "payable"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "PragmaKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "pragma"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "PrivateKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "private"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "PublicKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "public"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "PureKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "pure"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ReceiveKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "receive"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ReturnKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "return"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "ReturnsKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "returns"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "RevertKeyword"
  kind: "Scanner"
  versioned:
    0.8.4:
      trailingContext:
        scanner:
          terminal: "revert"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "SecondsKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "seconds"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "SolidityKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "solidity"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "StorageKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "storage"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "StringKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "string"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "StructKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "struct"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "SwitchKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "switch"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "SzaboKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      trailingContext:
        scanner:
          terminal: "szabo"
        notFollowedBy:
          reference: "IdentifierPart"
    0.7.0: null

- name: "ThrowKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      trailingContext:
        scanner:
          terminal: "throw"
        notFollowedBy:
          reference: "IdentifierPart"
    0.5.0: null

- name: "TrueKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "true"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "TryKeyword"
  kind: "Scanner"
  versioned:
    0.6.0:
      trailingContext:
        scanner:
          terminal: "try"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "TypeKeyword"
  kind: "Scanner"
  versioned:
    0.5.3:
      trailingContext:
        scanner:
          terminal: "type"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "UncheckedKeyword"
  kind: "Scanner"
  versioned:
    0.8.0:
      trailingContext:
        scanner:
          terminal: "unchecked"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "UsingKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "using"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "VarKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      trailingContext:
        scanner:
          terminal: "var"
        notFollowedBy:
          reference: "IdentifierPart"
    0.5.0: null

- name: "ViewKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "view"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "VirtualKeyword"
  kind: "Scanner"
  versioned:
    0.6.0:
      trailingContext:
        scanner:
          terminal: "virtual"
        notFollowedBy:
          reference: "IdentifierPart"

- name: "WeeksKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "weeks"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "WeiKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "wei"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "WhileKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "while"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "YearsKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      trailingContext:
        scanner:
          terminal: "years"
        notFollowedBy:
          reference: "IdentifierPart"
    0.5.0: null
