#!/bin/bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/../_common.sh"

RUST_DIR="$REPO_ROOT/crates/solidity/outputs/rust/slang_solidity"
TYPESCRIPT_DIR="$REPO_ROOT/crates/solidity/outputs/typescript/lib"

(
  printf "\n\n📜 Running changeset for TypeScript 📜\n\n\n"

  # Changeset will:
  # 1) Consume/delete the changeset files currently in "$REPO_ROOT/.changeset"
  # 2) Populate the CHANGELOG.md for the typescript package.
  # 3) Bump the version in its package.json accourdingly.
  _group_output changeset version
  _group_output npm install --package-lock-only

  printf "\n\n✅ TypeScript Success ✅\n\n\n"
)

NEW_VERSION=$(jq --raw-output ".version" "$TYPESCRIPT_DIR/package.json")

(
  printf "\n\n📜 Porting changes to Rust 📜\n\n\n"

  # Since changeset doesn't handle Cargo packages, we need to copy the changes over manually.
  _group_output cargo install cargo-edit
  _group_output cargo set-version "$NEW_VERSION" --workspace

  printf "\n\n✅ Rust Success ✅\n\n\n"
)

(
  printf "\n\n📜 Copying Common Files 📜\n\n\n"

  # Copy the new changelog generated by changeset to both repository root and the rust package.
  cp "$TYPESCRIPT_DIR/CHANGELOG.md" "$REPO_ROOT/CHANGELOG.md"
  cp "$TYPESCRIPT_DIR/CHANGELOG.md" "$RUST_DIR/CHANGELOG.md"

  # Update common files in both packages with repository root README and LICENSE files, in case they changed.
  for file in "README.md" "LICENSE"; do
    cp "$REPO_ROOT/$file" "$RUST_DIR/$file"
    cp "$REPO_ROOT/$file" "$TYPESCRIPT_DIR/$file"
  done

  printf "\n\n✅ Copy Success ✅\n\n\n"
)
