# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "LeadingTrivia"
  kind: "TriviaParser"
  unversioned:
    oneOrMore:
      choice:
        - reference: "Whitespace"
        - reference: "EndOfLine"
        - reference: "MultilineComment"
        - reference: "SingleLineComment"

- name: "TrailingTrivia"
  kind: "TriviaParser"
  unversioned:
    sequence:
      - optional:
          reference: "Whitespace"
      - optional:
          reference: "SingleLineComment"
      - reference: "EndOfLine"

- name: "EndOfFileTrivia"
  kind: "TriviaParser"
  unversioned:
    oneOrMore:
      choice:
        - reference: "Whitespace"
        - reference: "EndOfLine"
        - reference: "MultilineComment"
        - reference: "SingleLineComment"

- name: "Whitespace"
  kind: "Scanner"
  unversioned:
    oneOrMore:
      choice:
        - terminal: " "
        - terminal: "\t"

- name: "EndOfLine"
  kind: "Scanner"
  unversioned:
    sequence:
      - optional:
          terminal: "\r"
      - terminal: "\n"

- name: "MultilineComment"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "/*"
      - zeroOrMore:
          choice:
            - not:
                terminal: "*"
            - sequence:
                - terminal: "*"
                - not:
                    terminal: "/"
      - terminal: "*/"

- name: "SingleLineComment"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "//"
      - zeroOrMore:
          not:
            choice:
              - terminal: "\r"
              - terminal: "\n"
