# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "Expression"
  kind: "PrecedenceParser"
  versioned:
    0.4.11:
      operators:
        - name: "AssignmentExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "AssignmentOperator"

        - name: "ConditionalExpression"
          model: "UnaryPostfix"
          operator:
            reference: "ConditionalOperator"

        - name: "OrExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "OrOperator"

        - name: "AndExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "AndOperator"

        - name: "EqualityComparisonExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "EqualityComparisonOperator"

        - name: "OrderComparisonExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "OrderComparisonOperator"

        - name: "BitOrExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "BitOrOperator"

        - name: "BitXOrExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "BitXOrOperator"

        - name: "BitAndExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "BitAndOperator"

        - name: "ShiftExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "ShiftOperator"

        - name: "AddSubExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "AddSubOperator"

        - name: "MulDivModExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "MulDivModOperator"

        - name: "ExponentiationExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "ExponentiationOperator"

        - name: "UnaryPostfixExpression"
          model: "UnaryPostfix"
          operator:
            reference: "UnaryPostfixOperator"

        - name: "UnaryPrefixExpression"
          model: "UnaryPrefix"
          operator:
            reference: "UnaryPrefixOperator"

        - name: "FunctionCallExpression"
          model: "UnaryPostfix"
          operator:
            reference: "FunctionCallOperator"

        - name: "MemberAccessExpression"
          model: "UnaryPostfix"
          operator:
            reference: "MemberAccessOperator"

        - name: "IndexAccessExpression"
          model: "UnaryPostfix"
          operator:
            reference: "IndexAccessOperator"

      primaryExpression:
        reference: "PrimaryExpression"

    0.6.0:
      # ExponentiationExpression is now BinaryRightAssociative
      operators:
        - name: "AssignmentExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "AssignmentOperator"

        - name: "ConditionalExpression"
          model: "UnaryPostfix"
          operator:
            reference: "ConditionalOperator"

        - name: "OrExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "OrOperator"

        - name: "AndExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "AndOperator"

        - name: "EqualityComparisonExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "EqualityComparisonOperator"

        - name: "OrderComparisonExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "OrderComparisonOperator"

        - name: "BitOrExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "BitOrOperator"

        - name: "BitXOrExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "BitXOrOperator"

        - name: "BitAndExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "BitAndOperator"

        - name: "ShiftExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "ShiftOperator"

        - name: "AddSubExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "AddSubOperator"

        - name: "MulDivModExpression"
          model: "BinaryLeftAssociative"
          operator:
            reference: "MulDivModOperator"

        - name: "ExponentiationExpression"
          model: "BinaryRightAssociative"
          operator:
            reference: "ExponentiationOperator"

        - name: "UnaryPostfixExpression"
          model: "UnaryPostfix"
          operator:
            reference: "UnaryPostfixOperator"

        - name: "UnaryPrefixExpression"
          model: "UnaryPrefix"
          operator:
            reference: "UnaryPrefixOperator"

        - name: "FunctionCallExpression"
          model: "UnaryPostfix"
          operator:
            reference: "FunctionCallOperator"

        - name: "MemberAccessExpression"
          model: "UnaryPostfix"
          operator:
            reference: "MemberAccessOperator"

        - name: "IndexAccessExpression"
          model: "UnaryPostfix"
          operator:
            reference: "IndexAccessOperator"

      primaryExpression:
        reference: "PrimaryExpression"

- name: "AssignmentOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "Equal"
      - reference: "BarEqual"
      - reference: "CaretEqual"
      - reference: "AmpersandEqual"
      - reference: "LessThanLessThanEqual"
      - reference: "GreaterThanGreaterThanEqual"
      - reference: "GreaterThanGreaterThanGreaterThanEqual"
      - reference: "PlusEqual"
      - reference: "MinusEqual"
      - reference: "AsteriskEqual"
      - reference: "SlashEqual"
      - reference: "PercentEqual"

- name: "ConditionalOperator"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "QuestionMark"
      - reference: "Expression"
      - reference: "Colon"
      - reference: "Expression"

- name: "OrOperator"
  kind: "Parser"
  unversioned:
    reference: "BarBar"

- name: "AndOperator"
  kind: "Parser"
  unversioned:
    reference: "AmpersandAmpersand"

- name: "EqualityComparisonOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "EqualEqual"
      - reference: "BangEqual"

- name: "OrderComparisonOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "LessThan"
      - reference: "GreaterThan"
      - reference: "LessThanEqual"
      - reference: "GreaterThanEqual"

- name: "BitOrOperator"
  kind: "Parser"
  unversioned:
    reference: "Bar"

- name: "BitXOrOperator"
  kind: "Parser"
  unversioned:
    reference: "Caret"

- name: "BitAndOperator"
  kind: "Parser"
  unversioned:
    reference: "Ampersand"

- name: "ShiftOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "LessThanLessThan"
      - reference: "GreaterThanGreaterThan"
      - reference: "GreaterThanGreaterThanGreaterThan"

- name: "AddSubOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "Plus"
      - reference: "Minus"

- name: "MulDivModOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "Asterisk"
      - reference: "Slash"
      - reference: "Percent"

- name: "ExponentiationOperator"
  kind: "Parser"
  unversioned:
    reference: "AsteriskAsterisk"

- name: "UnaryPostfixOperator"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "PlusPlus"
      - reference: "MinusMinus"

- name: "UnaryPrefixOperator"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "PlusPlus"
        - reference: "MinusMinus"
        - reference: "Tilde"
        - reference: "Bang"
        - reference: "Minus"
        - reference: "Plus"
    0.5.0:
      # removed "Plus"
      choice:
        - reference: "PlusPlus"
        - reference: "MinusMinus"
        - reference: "Tilde"
        - reference: "Bang"
        - reference: "Minus"

- name: "FunctionCallOperator"
  kind: "Parser"
  versioned:
    0.4.11:
      reference: "ArgumentList"
    0.6.2:
      sequence:
        - zeroOrMore:
            reference: "FunctionCallOptions"
        - reference: "ArgumentList"
    0.8.0:
      sequence:
        - optional:
            reference: "FunctionCallOptions"
        - reference: "ArgumentList"

- name: "MemberAccessOperator"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Period"
      - choice:
          - reference: "Identifier"
          - reference: "AddressKeyword"

- name: "IndexAccessOperator"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBracket"
      expression:
        choice:
          - sequence:
              - reference: "Expression"
              - optional:
                  sequence:
                    - reference: "Colon"
                    - optional:
                        reference: "Expression"
          - sequence:
              - reference: "Colon"
              - optional:
                  reference: "Expression"
      close:
        reference: "CloseBracket"
