- name: "OpenParen"
  kind: "Scanner"
  unversioned:
    terminal: "("

- name: "CloseParen"
  kind: "Scanner"
  unversioned:
    terminal: ")"

- name: "OpenBracket"
  kind: "Scanner"
  unversioned:
    terminal: "["

- name: "CloseBracket"
  kind: "Scanner"
  unversioned:
    terminal: "]"

- name: "OpenBrace"
  kind: "Scanner"
  unversioned:
    terminal: "{"

- name: "CloseBrace"
  kind: "Scanner"
  unversioned:
    terminal: "}"

- name: "Comma"
  kind: "Scanner"
  unversioned:
    terminal: ","

- name: "Period"
  kind: "Scanner"
  unversioned:
    terminal: "."

- name: "QuestionMark"
  kind: "Scanner"
  unversioned:
    terminal: "?"

- name: "Semicolon"
  kind: "Scanner"
  unversioned:
    terminal: ";"

- name: "Colon"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: ":"
      notFollowedBy:
        terminal: "="

- name: "ColonEqual"
  kind: "Scanner"
  unversioned:
    terminal: ":="

- name: "Equal"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "="
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: ">"

- name: "EqualEqual"
  kind: "Scanner"
  unversioned:
    terminal: "=="

- name: "EqualGreaterThan"
  kind: "Scanner"
  unversioned:
    terminal: "=>"

- name: "Asterisk"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "*"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: "*"

- name: "AsteriskEqual"
  kind: "Scanner"
  unversioned:
    terminal: "*="

- name: "AsteriskAsterisk"
  kind: "Scanner"
  unversioned:
    terminal: "**"

- name: "Bar"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "|"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: "|"

- name: "BarEqual"
  kind: "Scanner"
  unversioned:
    terminal: "|="

- name: "BarBar"
  kind: "Scanner"
  unversioned:
    terminal: "||"

- name: "Ampersand"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "&"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: "&"

- name: "AmpersandEqual"
  kind: "Scanner"
  unversioned:
    terminal: "&="

- name: "AmpersandAmpersand"
  kind: "Scanner"
  unversioned:
    terminal: "&&"

- name: "LessThan"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "<"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: "<"

- name: "LessThanEqual"
  kind: "Scanner"
  unversioned:
    terminal: "<="

- name: "LessThanLessThan"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "<<"
      notFollowedBy:
        terminal: "="

- name: "LessThanLessThanEqual"
  kind: "Scanner"
  unversioned:
    terminal: "<<="

- name: "GreaterThan"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: ">"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: ">"

- name: "GreaterThanEqual"
  kind: "Scanner"
  unversioned:
    terminal: ">="

- name: "GreaterThanGreaterThan"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: ">>"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: ">"

- name: "GreaterThanGreaterThanEqual"
  kind: "Scanner"
  unversioned:
    terminal: ">>="

- name: "GreaterThanGreaterThanGreaterThan"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: ">>>"
      notFollowedBy:
        terminal: "="

- name: "GreaterThanGreaterThanGreaterThanEqual"
  kind: "Scanner"
  unversioned:
    terminal: ">>>="

- name: "Plus"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "+"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: "+"

- name: "PlusEqual"
  kind: "Scanner"
  unversioned:
    terminal: "+="

- name: "PlusPlus"
  kind: "Scanner"
  unversioned:
    terminal: "++"

- name: "Minus"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "-"
      notFollowedBy:
        choice:
          - terminal: "="
          - terminal: "-"
          - terminal: ">"

- name: "MinusEqual"
  kind: "Scanner"
  unversioned:
    terminal: "-="

- name: "MinusMinus"
  kind: "Scanner"
  unversioned:
    terminal: "--"

- name: "MinusGreaterThan"
  kind: "Scanner"
  unversioned:
    terminal: "->"

- name: "Slash"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "/"
      notFollowedBy:
        terminal: "="

- name: "SlashEqual"
  kind: "Scanner"
  unversioned:
    terminal: "/="

- name: "Percent"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "%"
      notFollowedBy:
        terminal: "="

- name: "PercentEqual"
  kind: "Scanner"
  unversioned:
    terminal: "%="

- name: "Bang"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "!"
      notFollowedBy:
        terminal: "="

- name: "BangEqual"
  kind: "Scanner"
  unversioned:
    terminal: "!="

- name: "Caret"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        terminal: "^"
      notFollowedBy:
        terminal: "="

- name: "CaretEqual"
  kind: "Scanner"
  unversioned:
    terminal: "^="

- name: "Tilde"
  kind: "Scanner"
  unversioned:
    terminal: "~"
