use lalrpop_util::lalrpop_mod;
use slang_solidity_v2_common::versions::LanguageVersion;

use crate::lexer::{LexemeKind, Lexer};
use crate::parser::parser_error::ParserError;

pub mod parser_helpers;

#[path = "consumer.generated.rs"]
pub mod consumer;

lalrpop_mod!(
    // Since this is generated code that we don't track, we rather not check for formatting
    #[rustfmt::skip]
    // Some of the code generated by LALRPOP doesn't follow these linting rules
    #[allow(clippy::elidable_lifetime_names)]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    #[allow(clippy::semicolon_if_nothing_returned)]
    #[allow(clippy::unnecessary_wraps)]
    #[allow(clippy::cloned_instead_of_copied)]
    #[allow(clippy::cast_sign_loss)]
    #[allow(clippy::too_many_lines)]
    #[allow(clippy::unused_self)]
    // We use this to allow wildcard import of node constructors
    #[allow(clippy::wildcard_imports)]
    pub(crate) grammar, "/parser/grammar.generated.rs"); // synthesized by LALRPOP

pub mod parser_error;

/// A Parser for Solidity Source Units
///
/// TODO(v2): Error recovery, for now we just fail
/// TODO(v2): Make the parser skip unique tokens, performance improvement
#[derive(Default)]
pub struct Parser;

impl Parser {
    /// Parse Solidity source with a custom consumer.
    pub fn parse_with_consumer<C: consumer::ParserConsumer>(
        input: &str,
        version: LanguageVersion,
        consumer: &C,
    ) -> Result<C::SourceUnit, ParserError> {
        let lexer = Lexer::new(input, version);
        let parser = grammar::SourceUnitParser::new();
        parser.parse(input, consumer, lexer).map_err(|e| e.into())
    }
}

/// Iterate over the lexemes and their offsets
///
/// TODO(v2): This iterator skips all trivia, we'll want to include it in
/// future versions
impl Iterator for Lexer<'_> {
    type Item = Result<(usize, LexemeKind, usize), ()>;

    fn next(&mut self) -> Option<Self::Item> {
        while let Some(lexeme) = self.next_lexeme() {
            if !lexeme.kind.is_trivia() {
                return Some(Ok((lexeme.range.start, lexeme.kind, lexeme.range.end)));
            }
        }
        None
    }
}
