use std::collections::BTreeSet;

use lalrpop_util::lalrpop_mod;
use slang_solidity_v2_common::diagnostics::kinds::syntax::{
    ExtraTerminal, UnexpectedEof, UnexpectedTerminal,
};
use slang_solidity_v2_common::diagnostics::DiagnosticCollection;
use slang_solidity_v2_common::terminals::TerminalKind;
use slang_solidity_v2_common::versions::LanguageVersion;
use slang_solidity_v2_cst::structured_cst::nodes::{
    new_source_unit, new_source_unit_members, SourceUnit,
};

use crate::lexer::{LexemeKind, Lexer};
use crate::parser::validation::validate_syntax_version;

mod parser_helpers;
mod validation;

lalrpop_mod!(
    // Since this is generated code that we don't track, we rather not check for formatting
    #[rustfmt::skip]
    // Some of the code generated by LALRPOP doesn't follow these linting rules
    #[allow(clippy::elidable_lifetime_names)]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    #[allow(clippy::semicolon_if_nothing_returned)]
    #[allow(clippy::unnecessary_wraps)]
    #[allow(clippy::cloned_instead_of_copied)]
    #[allow(clippy::cast_sign_loss)]
    #[allow(clippy::too_many_lines)]
    #[allow(clippy::unused_self)]
    // We use this to allow wildcard import of node constructors
    #[allow(clippy::wildcard_imports)]
    pub(crate) grammar, "/parser/grammar.generated.rs"); // synthesized by LALRPOP

/// The output of a parse operation, containing both the source unit and any diagnostics.
#[derive(Debug, PartialEq)]
pub struct ParseOutput {
    pub source_unit: SourceUnit,
    pub diagnostics: DiagnosticCollection,
}

/// A Parser for Solidity Source Units
///
/// TODO(v2): Error recovery, for now we return an empty [`SourceUnit`] on error
/// TODO(v2): Make the parser skip unique tokens, performance improvement
#[derive(Default)]
pub struct Parser;

impl Parser {
    pub fn parse(file_id: &str, source: &str, language_version: LanguageVersion) -> ParseOutput {
        let lexer = Lexer::new(source, language_version);
        let parser = grammar::SourceUnitParser::new();

        let mut diagnostics = DiagnosticCollection::default();
        match parser.parse(source, lexer) {
            Ok(source_unit) => {
                validate_syntax_version(&source_unit, language_version, file_id, &mut diagnostics);
                ParseOutput {
                    source_unit,
                    diagnostics,
                }
            }
            Err(e) => {
                convert_parse_error(file_id, &mut diagnostics, e);
                ParseOutput {
                    source_unit: new_source_unit(new_source_unit_members(vec![])),
                    diagnostics,
                }
            }
        }
    }
}

/// Convert a LALRPOP parse error into a `DiagnosticCollection`.
fn convert_parse_error(
    file_id: &str,
    diagnostics: &mut DiagnosticCollection,
    value: lalrpop_util::ParseError<usize, LexemeKind, ()>,
) {
    /// This function transforms the `String` representation returned by LALRPOP into an instance of `LexemeKind`
    ///
    /// TODO(v2): We may be able to improve on this if there's room for returning a discriminant instead of a string representation.
    /// [Ongoing discussion](https://github.com/lalrpop/lalrpop/issues/1089#issuecomment-4011323139)
    fn convert_expectations(expected: &[String]) -> BTreeSet<TerminalKind> {
        expected
            .iter()
            .map(|str| str.strip_prefix("L_").unwrap())
            .map(|str| str.parse::<LexemeKind>().unwrap())
            .map(|lexeme| TerminalKind::from(&lexeme))
            .collect()
    }

    match value {
        lalrpop_util::ParseError::UnrecognizedEof { location, expected } => {
            diagnostics.push(
                file_id.to_owned(),
                location..location,
                UnexpectedEof {
                    found: TerminalKind::UNRECOGNIZED,
                    expected: convert_expectations(&expected),
                },
            );
        }
        lalrpop_util::ParseError::UnrecognizedToken {
            token: (left, lexeme, right),
            expected,
        } => {
            diagnostics.push(
                file_id.to_owned(),
                left..right,
                UnexpectedTerminal {
                    found: TerminalKind::from(&lexeme),
                    expected: convert_expectations(&expected),
                },
            );
        }
        lalrpop_util::ParseError::ExtraToken {
            token: (left, lexeme, right),
        } => {
            diagnostics.push(
                file_id.to_owned(),
                left..right,
                ExtraTerminal {
                    found: TerminalKind::from(&lexeme),
                },
            );
        }
        lalrpop_util::ParseError::User { .. } => panic!("The parser should never return a user error, since we're not using any custom error types in our grammar"),
        lalrpop_util::ParseError::InvalidToken { .. } => panic!("The parser should never return an invalid token error, since it's not using the default lexer"),
    }
}

/// Iterate over the lexemes and their offsets
///
/// TODO(v2): This iterator skips all trivia, we'll want to include it in
/// future versions
impl Iterator for Lexer<'_> {
    type Item = Result<(usize, LexemeKind, usize), ()>;

    fn next(&mut self) -> Option<Self::Item> {
        while let Some(lexeme) = self.next_lexeme() {
            if !lexeme.kind.is_trivia() {
                return Some(Ok((lexeme.range.start, lexeme.kind, lexeme.range.end)));
            }
        }
        None
    }
}
