[package]
name = "codegen_spec"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
codegen_schema = { workspace = true }
codegen_utils = { workspace = true }
itertools = { workspace = true }
