use std::collections::{BTreeMap, BTreeSet};

use indexmap::IndexMap;
use inflector::Inflector;
use language_v2_definition::model;
use serde::ser::SerializeMap;
use serde::Serialize;

#[derive(Default, Serialize)]
pub struct IrModel {
    // Terminal nodes and whether they are unique or their value depends on the
    // content.
    pub terminals: BTreeMap<model::Identifier, Terminal>,

    pub sequences: BTreeMap<model::Identifier, Sequence>,
    pub choices: BTreeMap<model::Identifier, Choice>,
    pub collections: BTreeMap<model::Identifier, Collection>,

    // Externally-defined types, registered by the mutator and not generated by
    // the codegen templates.
    pub external_types: BTreeSet<model::Identifier>,
}

#[derive(Clone, Serialize)]
pub struct Terminal {
    pub is_unique: bool,
    pub is_identifier: bool,
}

#[derive(Clone, Serialize)]
pub struct Sequence {
    pub fields: Vec<Field>,
}

#[derive(Clone, Eq, Ord, PartialEq, PartialOrd)]
pub enum NodeType {
    Sequence(model::Identifier),
    Choice(model::Identifier),
    Collection(model::Identifier),
    Terminal(model::Identifier),
    UniqueTerminal(model::Identifier),
    // An externally-defined type, not generated from the language definition.
    // Behaves like `UniqueTerminal` in the IR/AST templates (bool field in
    // sequences, plain enum variant in choices, disallowed in collections).
    External(model::Identifier),
}

#[allow(clippy::struct_field_names)]
#[derive(Clone, Serialize)]
pub struct Field {
    pub label: model::Identifier,
    pub field_type: NodeType,
    pub is_optional: bool,
}

#[allow(clippy::struct_field_names)]
#[derive(Clone, Serialize)]
pub struct Choice {
    pub variants: Vec<NodeType>,
}

#[derive(Clone, Serialize)]
pub struct Collection {
    pub item_type: NodeType,
}

impl NodeType {
    pub fn as_identifier(&self) -> &model::Identifier {
        match self {
            NodeType::Sequence(identifier)
            | NodeType::Choice(identifier)
            | NodeType::Collection(identifier)
            | NodeType::Terminal(identifier)
            | NodeType::UniqueTerminal(identifier)
            | NodeType::External(identifier) => identifier,
        }
    }

    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Terminal(_) | Self::UniqueTerminal(_))
    }

    pub fn is_external(&self) -> bool {
        matches!(self, Self::External(_))
    }
}

impl PartialEq<model::Identifier> for NodeType {
    fn eq(&self, other: &model::Identifier) -> bool {
        self.as_identifier() == other
    }
}

impl Serialize for NodeType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let mut map = serializer.serialize_map(Some(5))?;
        let (identifier, kind, is_terminal, is_unique, is_external) = match self {
            NodeType::Sequence(identifier) => (identifier, "Sequence", false, false, false),
            NodeType::Choice(identifier) => (identifier, "Choice", false, false, false),
            NodeType::Collection(identifier) => (identifier, "Collection", false, false, false),
            NodeType::Terminal(identifier) => (identifier, "Terminal", true, false, false),
            NodeType::UniqueTerminal(identifier) => {
                (identifier, "UniqueTerminal", true, true, false)
            }
            NodeType::External(identifier) => (identifier, "External", false, false, true),
        };
        map.serialize_entry("name", identifier)?;
        map.serialize_entry("kind", kind)?;
        map.serialize_entry("is_terminal", &is_terminal)?;
        map.serialize_entry("is_unique", &is_unique)?;
        map.serialize_entry("is_external", &is_external)?;
        map.end()
    }
}

// Construction
impl IrModel {
    pub fn from_language(language: &model::Language) -> Self {
        let builder = IrModelBuilder::create(language);

        Self {
            terminals: builder.terminals,
            sequences: builder.sequences,
            choices: builder.choices,
            collections: builder.collections,
            external_types: BTreeSet::new(),
        }
    }

    pub fn from_model(model: &Self) -> Self {
        Self {
            terminals: model.terminals.clone(),
            sequences: model.sequences.clone(),
            choices: model.choices.clone(),
            collections: model.collections.clone(),
            external_types: model.external_types.clone(),
        }
    }
}

struct IrModelBuilder {
    pub node_types: BTreeMap<model::Identifier, NodeType>,
    pub terminals: BTreeMap<model::Identifier, Terminal>,
    pub sequences: BTreeMap<model::Identifier, Sequence>,
    pub choices: BTreeMap<model::Identifier, Choice>,
    pub collections: BTreeMap<model::Identifier, Collection>,
}

impl IrModelBuilder {
    fn create(language: &model::Language) -> Self {
        let mut builder = Self {
            node_types: BTreeMap::new(),
            terminals: BTreeMap::new(),
            sequences: BTreeMap::new(),
            choices: BTreeMap::new(),
            collections: BTreeMap::new(),
        };

        // First pass: collect types
        builder.collect_types(language);

        // Second pass: use them to define the nodes
        builder.collect_nodes(language);

        builder
    }

    fn collect_types(&mut self, language: &model::Language) {
        for item in language.items() {
            match item {
                model::Item::Struct { item } => {
                    self.node_types
                        .insert(item.name.clone(), NodeType::Sequence(item.name.clone()));
                }
                model::Item::Enum { item } => {
                    self.node_types
                        .insert(item.name.clone(), NodeType::Choice(item.name.clone()));
                }
                model::Item::Repeated { item } => {
                    self.node_types
                        .insert(item.name.clone(), NodeType::Collection(item.name.clone()));
                }
                model::Item::Separated { item } => {
                    self.node_types
                        .insert(item.name.clone(), NodeType::Collection(item.name.clone()));
                }
                model::Item::Precedence { item } => {
                    self.node_types
                        .insert(item.name.clone(), NodeType::Choice(item.name.clone()));
                    for expression in &item.precedence_expressions {
                        self.node_types.insert(
                            expression.name.clone(),
                            NodeType::Sequence(expression.name.clone()),
                        );
                    }
                }
                model::Item::Trivia { .. } => {
                    // These items are skipped by the parser.
                }
                model::Item::Keyword { item } => {
                    let node_type = if item.is_unique() {
                        NodeType::UniqueTerminal(item.name.clone())
                    } else {
                        NodeType::Terminal(item.name.clone())
                    };
                    self.node_types.insert(item.name.clone(), node_type);
                }
                model::Item::Token { item } => {
                    let node_type = if item.is_unique() {
                        NodeType::UniqueTerminal(item.name.clone())
                    } else {
                        NodeType::Terminal(item.name.clone())
                    };
                    self.node_types.insert(item.name.clone(), node_type);
                }
                model::Item::Fragment { .. } => {
                    // These items are inlined.
                }
            }
        }
    }

    fn collect_nodes(&mut self, language: &model::Language) {
        let identifier_tokens = language
            .contexts
            .iter()
            .filter_map(|context| context.identifier_token.clone())
            .collect::<BTreeSet<_>>();

        for item in language.items() {
            match item {
                model::Item::Struct { item } => {
                    self.add_struct_item(item);
                }
                model::Item::Enum { item } => {
                    self.add_enum_item(item);
                }
                model::Item::Repeated { item } => {
                    self.add_repeated_item(item);
                }
                model::Item::Separated { item } => {
                    self.add_separated_item(item);
                }
                model::Item::Precedence { item } => {
                    self.add_precedence_item(item);

                    for expr in &item.precedence_expressions {
                        self.add_precedence_expression(&item.name, expr);
                    }
                }
                model::Item::Trivia { .. } => {
                    // These items are skipped by the parser.
                }
                model::Item::Keyword { item } => {
                    self.terminals.insert(
                        item.name.clone(),
                        Terminal {
                            is_unique: item.is_unique(),
                            is_identifier: false,
                        },
                    );
                }
                model::Item::Token { item } => {
                    self.terminals.insert(
                        item.name.clone(),
                        Terminal {
                            is_unique: item.is_unique(),
                            is_identifier: identifier_tokens.contains(&item.name),
                        },
                    );
                }
                model::Item::Fragment { .. } => {
                    // These items are inlined.
                }
            }
        }
    }

    fn find_node_type(&self, identifier: &model::Identifier) -> NodeType {
        self.node_types
            .get(identifier)
            .cloned()
            .expect("can't determine NodeType for {identifier}")
    }

    fn add_struct_item(&mut self, item: &model::StructItem) {
        let parent_type = item.name.clone();
        let fields: Vec<_> = self.convert_fields(&item.fields).collect();

        self.sequences.insert(parent_type, Sequence { fields });
    }

    fn add_enum_item(&mut self, item: &model::EnumItem) {
        let parent_type = item.name.clone();

        let variants = item
            .variants
            .iter()
            .map(|variant| self.find_node_type(&variant.reference))
            .collect();

        self.choices.insert(parent_type, Choice { variants });
    }

    fn add_repeated_item(&mut self, item: &model::RepeatedItem) {
        let parent_type = item.name.clone();
        let item_type = self.find_node_type(&item.reference);

        self.collections
            .insert(parent_type, Collection { item_type });
    }

    fn add_separated_item(&mut self, item: &model::SeparatedItem) {
        let parent_type = item.name.clone();
        let item_type = self.find_node_type(&item.reference);

        self.collections
            .insert(parent_type, Collection { item_type });
    }

    fn add_precedence_item(&mut self, item: &model::PrecedenceItem) {
        let parent_type = item.name.clone();

        let precedence_expressions = item
            .precedence_expressions
            .iter()
            .map(|expression| &expression.name);

        let primary_expressions = item
            .primary_expressions
            .iter()
            .map(|expression| &expression.reference);

        let variants = precedence_expressions
            .chain(primary_expressions)
            .map(|item| self.find_node_type(item))
            .collect();

        self.choices.insert(parent_type, Choice { variants });
    }

    fn add_precedence_expression(
        &mut self,
        base_name: &model::Identifier,
        expression: &model::PrecedenceExpression,
    ) {
        let parent_type = expression.name.clone();

        let operator_fields = if expression.operators.len() == 1 {
            // If there's a single operator, we just use its fields directly
            self.convert_fields(&expression.operators[0].fields)
                .collect::<Vec<_>>()
        } else {
            // If there are multiple operators, we create a choice between them
            // They must have a single required field labeled "operator"
            //
            // Note: We use a set to avoid duplicate variants, in particular
            // exponentiation uses the same operator symbol for right and left
            // associative versions, although they live in different versions
            let variants: BTreeSet<_> = expression
                .operators
                .iter()
                .map(|operator| {
                    assert!(
                        operator.fields.len() == 1,
                        "Multiple operators with multiple fields are not supported"
                    );

                    let (ident, field) = operator.fields.first().unwrap();
                    assert_eq!(
                        ident,
                        &model::Identifier::from("operator"),
                        "Operator field must be labeled 'operator'"
                    );
                    if let model::Field::Required { reference } = field {
                        self.find_node_type(reference)
                    } else {
                        panic!("Operator field must be required");
                    }
                })
                .collect();

            let ident =
                model::Identifier::from(format!("{}_{}_Operator", base_name, expression.name));
            let label = ident.as_str().to_snake_case().into();

            // Insert the created choice
            self.choices.insert(
                ident.clone(),
                Choice {
                    variants: variants.into_iter().collect(),
                },
            );

            // The only field we care about then is a reference to that special operator
            vec![Field {
                label,
                field_type: NodeType::Choice(ident),
                is_optional: false,
            }]
        };

        let operand = |label: model::PredefinedLabel| Field {
            label: label.as_ref().into(),
            field_type: self.find_node_type(base_name),
            is_optional: false,
        };

        let mut fields = vec![];

        // All operators should have the same structure (validated at compile-time),
        // So let's pick up the first one to generate the types:
        match expression.operators[0].model {
            model::OperatorModel::Prefix => {
                fields.extend(operator_fields);
                fields.push(operand(model::PredefinedLabel::Operand));
            }
            model::OperatorModel::Postfix => {
                fields.push(operand(model::PredefinedLabel::Operand));
                fields.extend(operator_fields);
            }
            model::OperatorModel::BinaryLeftAssociative
            | model::OperatorModel::BinaryRightAssociative => {
                fields.push(operand(model::PredefinedLabel::LeftOperand));
                fields.extend(operator_fields);
                fields.push(operand(model::PredefinedLabel::RightOperand));
            }
        }

        self.sequences.insert(parent_type, Sequence { fields });
    }

    fn convert_fields<'a>(
        &'a self,
        fields: &'a IndexMap<model::Identifier, model::Field>,
    ) -> impl Iterator<Item = Field> + 'a {
        fields.iter().map(|(label, field)| {
            let (reference, is_optional) = match field {
                model::Field::Required { reference } => (reference, false),
                model::Field::Optional { reference, .. } => (reference, true),
            };
            let field_type = self.find_node_type(reference);

            Field {
                label: label.clone(),
                field_type,
                is_optional,
            }
        })
    }
}
