[package]
name = "codegen_runtime_npm_package"
description = "TypeScript runtime copied over by codegen"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true
