# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "IdentifierPath"
  kind: "Parser"
  unversioned:
    separatedBy:
      expression:
        reference: "Identifier"
      separator:
        reference: "Period"

- name: "Identifier"
  kind: "Scanner"
  unversioned:
    difference:
      minuend:
        reference: "RawIdentifier"
      subtrahend:
        choice:
          - reference: "NotAnIdentifierInAnyVersion"
          - reference: "NotAnIdentifierInSomeVersions"
          - reference: "FixedBytesType"
          - reference: "SignedFixedType"
          - reference: "UnsignedFixedType"
          - reference: "SignedIntegerType"
          - reference: "UnsignedIntegerType"

- name: "NotAnIdentifierInAnyVersion"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "abstract"
      - terminal: "address"
      - terminal: "after"
      - terminal: "anonymous"
      - terminal: "as"
      - terminal: "assembly"
      - terminal: "bool"
      - terminal: "break"
      - terminal: "byte"
      - terminal: "case"
      - terminal: "catch"
      - terminal: "constant"
      - terminal: "continue"
      - terminal: "contract"
      - terminal: "days"
      - terminal: "default"
      - terminal: "delete"
      - terminal: "do"
      - terminal: "else"
      - terminal: "enum"
      - terminal: "ether"
      - terminal: "event"
      - terminal: "external"
      - terminal: "false"
      - terminal: "final"
      - terminal: "for"
      - terminal: "function"
      - terminal: "hex"
      - terminal: "hours"
      - terminal: "if"
      - terminal: "import"
      - terminal: "in"
      - terminal: "indexed"
      - terminal: "inline"
      - terminal: "interface"
      - terminal: "internal"
      - terminal: "is"
      - terminal: "let"
      - terminal: "library"
      - terminal: "mapping"
      - terminal: "match"
      - terminal: "memory"
      - terminal: "minutes"
      - terminal: "modifier"
      - terminal: "new"
      - terminal: "null"
      - terminal: "of"
      - terminal: "payable"
      - terminal: "pragma"
      - terminal: "private"
      - terminal: "public"
      - terminal: "pure"
      - terminal: "relocatable"
      - terminal: "return"
      - terminal: "returns"
      - terminal: "seconds"
      - terminal: "static"
      - terminal: "storage"
      - terminal: "string"
      - terminal: "struct"
      - terminal: "switch"
      - terminal: "throw"
      - terminal: "true"
      - terminal: "try"
      - terminal: "type"
      - terminal: "typeof"
      - terminal: "using"
      - terminal: "var"
      - terminal: "view"
      - terminal: "weeks"
      - terminal: "wei"
      - terminal: "while"
      - terminal: "years"

- name: "NotAnIdentifierInSomeVersions"
  kind: "Scanner"
  versioned:
    0.4.11:
      choice:
        - terminal: "finney"
        - terminal: "szabo"
    0.5.0:
      choice:
        - terminal: "finney"
        - terminal: "szabo"
        # added
        - terminal: "alias"
        - terminal: "apply"
        - terminal: "auto"
        - terminal: "calldata"
        - terminal: "constructor"
        - terminal: "copyof"
        - terminal: "define"
        - terminal: "emit"
        - terminal: "immutable"
        - terminal: "implements"
        - terminal: "macro"
        - terminal: "mutable"
        - terminal: "override"
        - terminal: "partial"
        - terminal: "promise"
        - terminal: "reference"
        - terminal: "sealed"
        - terminal: "sizeof"
        - terminal: "supports"
        - terminal: "typedef"
        - terminal: "unchecked"
    0.6.0:
      choice:
        - terminal: "finney"
        - terminal: "szabo"
        - terminal: "alias"
        - terminal: "apply"
        - terminal: "auto"
        - terminal: "calldata"
        - terminal: "constructor"
        - terminal: "copyof"
        - terminal: "define"
        - terminal: "emit"
        - terminal: "immutable"
        - terminal: "implements"
        - terminal: "macro"
        - terminal: "mutable"
        - terminal: "override"
        - terminal: "partial"
        - terminal: "promise"
        - terminal: "reference"
        - terminal: "sealed"
        - terminal: "sizeof"
        - terminal: "supports"
        - terminal: "typedef"
        - terminal: "unchecked"
        # added
        - terminal: "fallback"
        - terminal: "receive"
        - terminal: "virtual"
    0.7.0:
      choice:
        # - terminal: "finney"
        # - terminal: "szabo"
        - terminal: "alias"
        - terminal: "apply"
        - terminal: "auto"
        - terminal: "calldata"
        - terminal: "constructor"
        - terminal: "copyof"
        - terminal: "define"
        - terminal: "emit"
        - terminal: "immutable"
        - terminal: "implements"
        - terminal: "macro"
        - terminal: "mutable"
        - terminal: "override"
        - terminal: "partial"
        - terminal: "promise"
        - terminal: "reference"
        - terminal: "sealed"
        - terminal: "sizeof"
        - terminal: "supports"
        - terminal: "typedef"
        - terminal: "unchecked"
        - terminal: "fallback"
        - terminal: "receive"
        - terminal: "virtual"
        # added
        - terminal: "gwei"

- name: "RawIdentifier"
  kind: "Scanner"
  unversioned:
    sequence:
      - reference: "IdentifierStart"
      - zeroOrMore:
          reference: "IdentifierPart"

- name: "IdentifierStart"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "_"
      - terminal: "$"
      - range:
          from: "a"
          to: "z"
      - range:
          from: "A"
          to: "Z"

- name: "IdentifierPart"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "IdentifierStart"
      - range:
          from: "0"
          to: "9"
