version: "3"

tasks:
  "default":
    desc: "Run code generation scripts for different crates in the codebase."
    deps:
      - "v1"
      - "v2"

  "v1":
    desc: "Run the V1 code generation scripts."
    cmds:
      - "cargo run --bin codegen_runner"

  "v2":
    desc: "Run the V2 code generation scripts."
    cmds:
      - "cargo run --bin codegen_v2_runner"
