[workspace]
members = [
    "crates/codegen/schema",
    "crates/codegen/ebnf",
    "crates/codegen/parser",
    "crates/codegen/spec",
    "crates/codegen/utils",
    "crates/solidity/outputs/parser",
]

[profile.dev]
debug = 0
incremental = true
