[workspace]
members = [
    "crates/codegen/schema",
    "crates/codegen/spec",
    "crates/codegen/utils",
    "crates/parsers/ebnf",
    "crates/parsers/solidity",
    "crates/solc_proxy",
]

[profile.dev]
debug = 0
incremental = true
