[workspace]
members = [
    "crates/codegen/schema",
    "crates/codegen/ebnf",
    "crates/codegen/parser",
    "crates/codegen/spec",
    "crates/codegen/utils",
    "crates/solidity/outputs/documentation",
    "crates/solidity/outputs/rust_lib",
    "crates/solidity/outputs/cli",
    "crates/solidity/outputs/typescript_lib",
]

[profile.dev]
debug = 0
incremental = true

[profile.release]
lto = true
