# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "Block"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBrace"
      expression:
        zeroOrMore:
          choice:
            - reference: "Statement"
            - reference: "UncheckedBlock"
      close:
        reference: "CloseBrace"

- name: "UncheckedBlock"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "UncheckedKeyword"
      - reference: "Block"

- name: "Statement"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "Block"
      - reference: "SimpleStatement"
      - reference: "IfStatement"
      - reference: "ForStatement"
      - reference: "WhileStatement"
      - reference: "DoWhileStatement"
      - reference: "ContinueStatement"
      - reference: "BreakStatement"
      - reference: "TryStatement"
      - reference: "ReturnStatement"
      - reference: "EmitStatement"
      - reference: "RevertStatement"
      - reference: "DeleteStatement"
      - reference: "AssemblyStatement"

- name: "SimpleStatement"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "TupleDeconstructionStatement"
      - reference: "VariableDeclarationStatement"
      - reference: "ExpressionStatement"

- name: "ExpressionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        reference: "Expression"
      terminator:
        reference: "Semicolon"
