# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "Block"
  kind: "Parser"
  versioned:
    0.4.11:
      delimitedBy:
        open:
          reference: "OpenBrace"
        expression:
          zeroOrMore:
            reference: "Statement"
        close:
          reference: "CloseBrace"
    0.8.0:
      delimitedBy:
        open:
          reference: "OpenBrace"
        expression:
          zeroOrMore:
            choice:
              - reference: "Statement"
              - reference: "UncheckedBlock"
        close:
          reference: "CloseBrace"

- name: "UncheckedBlock"
  kind: "Parser"
  versioned:
    0.8.0:
      sequence:
        - reference: "UncheckedKeyword"
        - reference: "Block"

- name: "Statement"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "Block"
        - reference: "SimpleStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "ReturnStatement"
        - reference: "ThrowStatement"
        - reference: "RevertStatement"
        - reference: "DeleteStatement"
        - reference: "AssemblyStatement"
    0.4.21:
      # added "EmitStatement"
      choice:
        - reference: "Block"
        - reference: "SimpleStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "ReturnStatement"
        - reference: "EmitStatement"
        - reference: "ThrowStatement"
        - reference: "RevertStatement"
        - reference: "DeleteStatement"
        - reference: "AssemblyStatement"
    0.5.0:
      # removed: "ThrowStatement"
      choice:
        - reference: "Block"
        - reference: "SimpleStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "ReturnStatement"
        - reference: "EmitStatement"
        - reference: "RevertStatement"
        - reference: "DeleteStatement"
        - reference: "AssemblyStatement"
    0.6.0:
      # added: "TryStatement"
      choice:
        - reference: "Block"
        - reference: "SimpleStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "TryStatement"
        - reference: "ReturnStatement"
        - reference: "EmitStatement"
        - reference: "RevertStatement"
        - reference: "DeleteStatement"
        - reference: "AssemblyStatement"

- name: "SimpleStatement"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "TupleDeconstructionStatement"
      - reference: "VariableDeclarationStatement"
      - reference: "ExpressionStatement"

- name: "ExpressionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        reference: "Expression"
      terminator:
        reference: "Semicolon"
