# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "TupleDeconstructionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - delimitedBy:
              open:
                reference: "OpenParen"
              expression:
                optional:
                  separatedBy:
                    separator:
                      reference: "Comma"
                    expression:
                      optional:
                        choice:
                          - sequence:
                              - reference: "TypeName"
                              - optional:
                                  reference: "DataLocation"
                              - reference: "Identifier"
                          - sequence:
                              - optional:
                                  reference: "DataLocation"
                              - reference: "Identifier"
              close:
                reference: "CloseParen"
          - reference: "Equal"
          - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "VariableDeclarationStatement"
  kind: "Parser"
  versioned:
    0.4.11:
      terminatedBy:
        expression:
          sequence:
            - choice:
                - sequence:
                    - reference: "TypeName"
                    - optional:
                        reference: "DataLocation"
                - reference: "VarKeyword"
            - reference: "Identifier"
            - optional:
                sequence:
                  - reference: "Equal"
                  - reference: "Expression"
        terminator:
          reference: "Semicolon"
    0.5.0: # removed "VarKeyword"
      terminatedBy:
        expression:
          sequence:
            - reference: "TypeName"
            - optional:
                reference: "DataLocation"
            - reference: "Identifier"
            - optional:
                sequence:
                  - reference: "Equal"
                  - reference: "Expression"
        terminator:
          reference: "Semicolon"

- name: "DataLocation"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "MemoryKeyword"
        - reference: "StorageKeyword"
    0.5.0:
      choice:
        - reference: "MemoryKeyword"
        - reference: "StorageKeyword"
        - reference: "CalldataKeyword"
