# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "NumericLiteral"
  kind: "Parser"
  unversioned:
    sequence:
      - choice:
          - reference: "HexLiteral"
          - reference: "DecimalLiteral"
      - optional:
          reference: "NumberUnit"

- name: "HexLiteral"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "0x"
      - separatedBy:
          separator: "_"
          expression:
            oneOrMore:
              reference: "HexCharacter"

- name: "DecimalLiteral"
  kind: "Scanner"
  unversioned:
    sequence:
      - choice:
          - sequence:
              - reference: "DecimalNumber"
              - optional:
                  sequence:
                    - terminal: "."
                    - reference: "DecimalNumber"
          - sequence:
              - terminal: "."
              - reference: "DecimalNumber"
      - optional:
          reference: "DecimalExponent"

- name: "DecimalNumber"
  kind: "Scanner"
  unversioned:
    separatedBy:
      separator: "_"
      expression:
        oneOrMore:
          range:
            from: "0"
            to: "9"

- name: "DecimalExponent"
  kind: "Scanner"
  unversioned:
    sequence:
      - choice:
          - terminal: "e"
          - terminal: "E"
      - optional:
          terminal: "-"
      - reference: "DecimalNumber"

- name: "NumberUnit"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "DaysKeyword"
      - reference: "EtherKeyword"
      - reference: "FinneyKeyword"
      - reference: "GweiKeyword"
      - reference: "HoursKeyword"
      - reference: "MinutesKeyword"
      - reference: "SecondsKeyword"
      - reference: "SzaboKeyword"
      - reference: "WeeksKeyword"
      - reference: "WeiKeyword"
      - reference: "YearsKeyword"
