# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "ContractDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - optional:
          reference: "AbstractKeyword"
      - reference: "ContractKeyword"
      - reference: "Identifier"
      - optional:
          reference: "InheritanceSpecifierList"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            zeroOrMore:
              reference: "ContractBodyElement"
          close:
            reference: "CloseBrace"

- name: "InheritanceSpecifierList"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IsKeyword"
      - separatedBy:
          separator:
            reference: "Comma"
          expression:
            reference: "InheritanceSpecifier"

- name: "InheritanceSpecifier"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IdentifierPath"
      - optional:
          reference: "ArgumentList"

- name: "ContractBodyElement"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "UsingDirective"
      - reference: "ConstructorDefinition"
      - reference: "FunctionDefinition"
      - reference: "FallbackFunctionDefinition"
      - reference: "ReceiveFunctionDefinition"
      - reference: "ModifierDefinition"
      - reference: "StructDefinition"
      - reference: "EnumDefinition"
      - reference: "UserDefinedValueTypeDefinition"
      - reference: "EventDefinition"
      - reference: "ErrorDefinition"
      - reference: "StateVariableDeclaration"
