# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ErrorDefinition"
  kind: "Parser"
  versioned:
    0.8.4:
      terminatedBy:
        parser:
          sequence:
            - reference: "ErrorKeyword"
            - reference: "Identifier"
            - delimitedBy:
                open:
                  reference: "OpenParen"
                parser:
                  optional:
                    reference: "ErrorParametersList"
                close:
                  reference: "CloseParen"
        terminator:
          reference: "Semicolon"

- name: "ErrorParametersList"
  kind: "Parser"
  versioned:
    0.8.4:
      separatedBy:
        separator:
          reference: "Comma"
        parser:
          reference: "ErrorParameter"

- name: "ErrorParameter"
  kind: "Parser"
  versioned:
    0.8.4:
      sequence:
        - reference: "TypeName"
        - optional:
            reference: "Identifier"
