# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ErrorDefinition"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "ErrorKeyword"
          - reference: "Identifier"
          - delimitedBy:
              open:
                reference: "OpenParen"
              expression:
                optional:
                  separatedBy:
                    separator:
                      reference: "Comma"
                    expression:
                      reference: "ErrorParameter"
              close:
                reference: "CloseParen"
      terminator:
        reference: "Semicolon"

- name: "ErrorParameter"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "TypeName"
      - optional:
          reference: "Identifier"
