# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "TryStatement"
  kind: "Parser"
  versioned:
    0.6.0:
      sequence:
        - reference: "TryKeyword"
        - reference: "Expression"
        - optional:
            reference: "ReturnsDeclaration"
        - reference: "Block"
        - reference: "CatchClausesList"

- name: "CatchClausesList"
  kind: "Parser"
  versioned:
    0.6.0:
      oneOrMore:
        reference: "CatchClause"

- name: "CatchClause"
  kind: "Parser"
  versioned:
    0.6.0:
      sequence:
        - reference: "CatchKeyword"
        - optional:
            reference: "CatchClauseError"
        - reference: "Block"

- name: "CatchClauseError"
  kind: "Parser"
  versioned:
    0.6.0:
      sequence:
        - optional:
            reference: "Identifier"
        - reference: "ParametersDeclaration"

- name: "RevertStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "RevertKeyword"
          - optional:
              reference: "IdentifierPath"
          - reference: "ArgumentsDeclaration"
      terminator:
        reference: "Semicolon"

- name: "ThrowStatement"
  kind: "Parser"
  versioned:
    0.4.11:
      terminatedBy:
        parser:
          reference: "ThrowKeyword"
        terminator:
          reference: "Semicolon"
    0.5.0: null
