# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "StructDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "StructKeyword"
      - reference: "Identifier"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          parser:
            optional:
              reference: "StructMembers"
          close:
            reference: "CloseBrace"

- name: "StructMembers"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "StructMember"

- name: "StructMember"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "TypeName"
          - reference: "Identifier"
      terminator:
        reference: "Semicolon"
