[package]
name = "language_v2_macros"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
language_v2_definition = { workspace = true }

[lints]
workspace = true
