    define_payload_tests!(flat_imports_mooniswap, "flat_imports_mooniswap");
    define_payload_tests!(circular_imports_weighted_pool, "circular_imports_weighted_pool");
    define_payload_tests!(protocol_uniswap, "protocol_uniswap");
    define_payload_tests!(protocol_multicall3, "protocol_multicall3");
    define_payload_tests!(protocol_create_x, "protocol_create_x");
    define_payload_tests!(protocol_ui_pool_data_provider_v3, "protocol_ui_pool_data_provider_v3");
    define_payload_tests!(largest_file_trivia_one_step_leverage_f, "largest_file_trivia_one_step_leverage_f");
    define_payload_tests!(median_file_safe_math, "median_file_safe_math");
    define_payload_tests!(three_quarters_file_merkle_proof, "three_quarters_file_merkle_proof");
