# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "PrimaryExpression"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "NewExpression"
        - reference: "TupleExpression"
        - reference: "ArrayExpression"
        - reference: "BooleanExpression"
        - reference: "NumericExpression"
        - reference: "StringExpression"
        - reference: "ElementaryType"
        - reference: "Identifier"
    0.5.3:
      # added: TypeExpression
      choice:
        - reference: "NewExpression"
        - reference: "TupleExpression"
        - reference: "TypeExpression"
        - reference: "ArrayExpression"
        - reference: "BooleanExpression"
        - reference: "NumericExpression"
        - reference: "StringExpression"
        - reference: "ElementaryType"
        - reference: "Identifier"

- name: "TypeExpression"
  kind: "Parser"
  versioned:
    0.5.3:
      sequence:
        - reference: "TypeKeyword"
        - delimitedBy:
            open:
              reference: "OpenParen"
            parser:
              reference: "TypeName"
            close:
              reference: "CloseParen"

- name: "NewExpression"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "NewKeyword"
      - reference: "TypeName"

- name: "TupleExpression"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      parser:
        reference: "TupleValues"
      close:
        reference: "CloseParen"

- name: "TupleValues"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        optional:
          reference: "Expression"

- name: "ArrayExpression"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBracket"
      parser:
        reference: "ArrayValues"
      close:
        reference: "CloseBracket"

- name: "ArrayValues"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "Expression"

- name: "BooleanExpression"
  kind: "Parser"
  inlined: true
  unversioned:
    choice:
      - reference: "TrueKeyword"
      - reference: "FalseKeyword"
