# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "PragmaDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "PragmaKeyword"
          - choice:
              - reference: "VersionPragma"
              - reference: "ABICoderPragma"
              - reference: "ExperimentalPragma"
      terminator:
        reference: "Semicolon"

- name: "VersionPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "SolidityKeyword"
      - oneOrMore:
          reference: "VersionPragmaExpression"

- name: "VersionPragmaExpression"
  kind: "PrecedenceParser"
  unversioned:
    definitions:
      - name: "VersionPragmaAlternatives"
        model: "BinaryLeftAssociative"
        operator:
          reference: "BarBar"
      - name: "VersionPragmaRange"
        model: "BinaryLeftAssociative"
        operator:
          reference: "Minus"
      - name: "VersionPragmaComparator"
        model: "UnaryPrefix"
        operator:
          choice:
            - reference: "Caret"
            - reference: "Tilde"
            - reference: "Equal"
            - reference: "LessThan"
            - reference: "GreaterThan"
            - reference: "LessThanEqual"
            - reference: "GreaterThanEqual"

    primaryExpression:
      reference: "VersionPragmaSpecifier"

- name: "VersionPragmaSpecifier"
  kind: "Parser"
  unversioned:
    separatedBy:
      expression:
        reference: "VersionPragmaValue"
      separator:
        reference: "Period"

- name: "VersionPragmaValue"
  kind: "Scanner"
  unversioned:
    oneOrMore:
      choice:
        - range:
            from: "0"
            to: "9"
        - terminal: "x"
        - terminal: "X"
        - terminal: "*"

- name: "ABICoderPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AbicoderKeyword"
      - reference: "Identifier"

- name: "ExperimentalPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ExperimentalKeyword"
      - reference: "Identifier"
