[package]
name = "codegen_runtime_cargo_crate"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

description = "Cargo runtime copied over by codegen"

# __RUST_PRODUCT_CRATE_FEATURES__ (keep in sync)
[features]
default = []
__private_wasm_apis = []
__private_testing_utils = []

[dependencies]

[lints]
workspace = true
