[package]
name = "codegen_runtime_cargo_crate"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

description = "Cargo runtime copied over by codegen"

# __RUST_PRODUCT_CRATE_FEATURES__ (keep in sync)
[features]
default = []
__private_ariadne_errors = ["dep:ariadne"]
__private_wasm_apis = []
__private_testing_utils = []

[dependencies]
ariadne = { workspace = true, optional = true }
metaslang_bindings = { workspace = true }
metaslang_cst = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
