[package]
name = "solidity_schema"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[build-dependencies]
anyhow = { workspace = true }
bson = { workspace = true }
codegen_schema = { workspace = true }
codegen_utils = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bson = { workspace = true }
codegen_schema = { workspace = true }
