[package]
name = "codegen_testing"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.66", features = ["std", "backtrace"] }
codegen_schema = { path = "../schema" }
codegen_utils = { path = "../utils" }
semver = "1.0.9"
