# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "UserDefinedValueTypeDefinition"
  kind: "Parser"
  versioned:
    0.8.8:
      terminatedBy:
        expression:
          sequence:
            - reference: "TypeKeyword"
            - reference: "Identifier"
            - reference: "IsKeyword"
            - reference: "ElementaryType"
        terminator:
          reference: "Semicolon"
