# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "StateVariableDefinition"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "TypeName"
          - optional:
              reference: "StateVariableAttributesList"
          - reference: "Identifier"
          - optional:
              sequence:
                - reference: "Equal"
                - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "StateVariableAttributesList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "StateVariableAttribute"

- name: "StateVariableAttribute"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "OverrideSpecifier"
        - reference: "ConstantKeyword"
        - reference: "InternalKeyword"
        - reference: "PrivateKeyword"
        - reference: "PublicKeyword"
    0.6.5:
      # added: ImmutableKeyword
      choice:
        - reference: "OverrideSpecifier"
        - reference: "ConstantKeyword"
        - reference: "ImmutableKeyword"
        - reference: "InternalKeyword"
        - reference: "PrivateKeyword"
        - reference: "PublicKeyword"
