[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
ariadne = "0.1.5"
chumsky = { path = "chumsky" }
proc-macro2 = "1.0.37"
quote = "1.0.18"
