# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ConstantDefinition"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "TypeName"
          - reference: "ConstantKeyword"
          - reference: "Identifier"
          - reference: "Equal"
          - reference: "Expression"
      terminator:
        reference: "Semicolon"
