# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "EnumDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "EnumKeyword"
      - reference: "Identifier"
      - delimitedBy:
          open: "{"
          expression:
            optional:
              separatedBy:
                separator: ","
                expression:
                  reference: "Identifier"
          close: "}"
