# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "StringExpression"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - oneOrMore:
            reference: "HexStringLiteral"
        - oneOrMore:
            reference: "AsciiStringLiteral"
    0.7.0:
      # added "UnicodeStringLiteral"
      choice:
        - oneOrMore:
            reference: "HexStringLiteral"
        - oneOrMore:
            reference: "AsciiStringLiteral"
        - oneOrMore:
            reference: "UnicodeStringLiteral"

- name: "HexStringLiteral"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "hex"
      - choice:
          - sequence:
              - terminal: '"'
              - optional:
                  reference: "PossiblySeparatedPairsOfHexDigits"
              - terminal: '"'
          - sequence:
              - terminal: "'"
              - optional:
                  reference: "PossiblySeparatedPairsOfHexDigits"
              - terminal: "'"

- name: "PossiblySeparatedPairsOfHexDigits"
  kind: "Scanner"
  unversioned:
    sequence:
      - repeat:
          min: 2
          max: 2
          expression:
            reference: "HexCharacter"
      - zeroOrMore:
          sequence:
            - optional:
                terminal: "_"
            - repeat:
                min: 2
                max: 2
                expression:
                  reference: "HexCharacter"

- name: "HexCharacter"
  kind: "Scanner"
  unversioned:
    choice:
      - range:
          from: "0"
          to: "9"
      - range:
          from: "a"
          to: "f"
      - range:
          from: "A"
          to: "F"

- name: "AsciiStringLiteral"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "SingleQuotedAsciiStringLiteral"
      - reference: "DoubleQuotedAsciiStringLiteral"

- name: "SingleQuotedAsciiStringLiteral"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "'"
      - zeroOrMore:
          choice:
            - reference: "EscapeSequence"
            - difference:
                minuend:
                  range:
                    from: " "
                    to: "~"
                subtrahend:
                  choice:
                    - terminal: "'"
                    - terminal: "\\"
      - terminal: "'"

- name: "DoubleQuotedAsciiStringLiteral"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: '"'
      - zeroOrMore:
          choice:
            - reference: "EscapeSequence"
            - difference:
                minuend:
                  range:
                    from: " "
                    to: "~"
                subtrahend:
                  choice:
                    - terminal: '"'
                    - terminal: "\\"
      - terminal: '"'

- name: "UnicodeStringLiteral"
  kind: "Scanner"
  versioned:
    0.7.0:
      choice:
        - reference: "SingleQuotedUnicodeStringLiteral"
        - reference: "DoubleQuotedUnicodeStringLiteral"

- name: "SingleQuotedUnicodeStringLiteral"
  kind: "Scanner"
  versioned:
    0.7.0:
      sequence:
        - terminal: "unicode'"
        - zeroOrMore:
            choice:
              - reference: "EscapeSequence"
              - not:
                  choice:
                    - terminal: "'"
                    - terminal: "\\"
                    - terminal: "\n"
                    - terminal: "\r"
        - terminal: "'"

- name: "DoubleQuotedUnicodeStringLiteral"
  kind: "Scanner"
  versioned:
    0.7.0:
      sequence:
        - terminal: 'unicode"'
        - zeroOrMore:
            choice:
              - reference: "EscapeSequence"
              - not:
                  choice:
                    - terminal: '"'
                    - terminal: "\\"
                    - terminal: "\n"
                    - terminal: "\r"
        - terminal: '"'

- name: "EscapeSequence"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "\\"
      - choice:
          - reference: "AsciiEscape"
          - reference: "HexByteEscape"
          - reference: "UnicodeEscape"

- name: "AsciiEscape"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "n"
      - terminal: "r"
      - terminal: "t"
      - terminal: "'"
      - terminal: '"'
      - terminal: "\\"
      - terminal: "\n"
      - terminal: "\r"

- name: "HexByteEscape"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "x"
      - repeat:
          min: 2
          max: 2
          expression:
            reference: "HexCharacter"

- name: "UnicodeEscape"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "u"
      - repeat:
          min: 4
          max: 4
          expression:
            reference: "HexCharacter"
