# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ImportDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "ImportKeyword"
          - choice:
              - reference: "PathImport"
              - reference: "NamedImport"
              - reference: "DeconstructionImport"
      terminator:
        reference: "Semicolon"

- name: "PathImport"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AsciiStringLiteral"
      - optional:
          sequence:
            - reference: "AsKeyword"
            - reference: "Identifier"

- name: "NamedImport"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Asterisk"
      - reference: "AsKeyword"
      - reference: "Identifier"
      - reference: "FromKeyword"
      - reference: "AsciiStringLiteral"

- name: "DeconstructionImport"
  kind: "Parser"
  unversioned:
    sequence:
      - delimitedBy:
          open:
            reference: "OpenBrace"
          parser:
            reference: "DeconstructionImportSymbolsList"
          close:
            reference: "CloseBrace"
      - reference: "FromKeyword"
      - reference: "AsciiStringLiteral"

- name: "DeconstructionImportSymbolsList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "DeconstructionImportSymbol"

- name: "DeconstructionImportSymbol"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Identifier"
      - optional:
          sequence:
            - reference: "AsKeyword"
            - reference: "Identifier"

- name: "UsingDirective"
  kind: "Parser"
  versioned:
    0.4.11:
      terminatedBy:
        parser:
          sequence:
            - reference: "UsingKeyword"
            - reference: "UsingDirectivePath"
            - reference: "ForKeyword"
            - choice:
                - reference: "Asterisk"
                - reference: "TypeName"
        terminator:
          reference: "Semicolon"
    # Added an optional `global` keyword and `UsingDirectiveDeconstruction`
    0.8.13:
      terminatedBy:
        parser:
          sequence:
            - reference: "UsingKeyword"
            - choice:
                - reference: "UsingDirectivePath"
                - reference: "UsingDirectiveDeconstruction"
            - reference: "ForKeyword"
            - choice:
                - reference: "Asterisk"
                - reference: "TypeName"
            - optional:
                reference: "GlobalKeyword"
        terminator:
          reference: "Semicolon"

- name: "UsingDirectivePath"
  kind: "Parser"
  unversioned:
    reference: "IdentifierPath"

- name: "UsingDirectiveDeconstruction"
  kind: "Parser"
  versioned:
    0.8.13:
      delimitedBy:
        open:
          reference: "OpenBrace"
        parser:
          reference: "UsingDirectiveSymbols"
        close:
          reference: "CloseBrace"

- name: "UsingDirectiveSymbols"
  kind: "Parser"
  versioned:
    0.8.13:
      separatedBy:
        separator:
          reference: "Comma"
        parser:
          reference: "UsingDirectiveSymbol"

- name: "UsingDirectiveSymbol"
  kind: "Parser"
  versioned:
    0.8.13:
      reference: "IdentifierPath"
    0.8.19:
      sequence:
        - reference: "IdentifierPath"
        - optional:
            sequence:
              - reference: "AsKeyword"
              - reference: "UsingDirectiveOperator"

- name: "UsingDirectiveOperator"
  kind: "Parser"
  inlined: true
  versioned:
    0.8.19:
      choice:
        - reference: "Ampersand"
        - reference: "Asterisk"
        - reference: "BangEqual"
        - reference: "Bar"
        - reference: "Caret"
        - reference: "EqualEqual"
        - reference: "GreaterThan"
        - reference: "GreaterThanEqual"
        - reference: "LessThan"
        - reference: "LessThanEqual"
        - reference: "Minus"
        - reference: "Percent"
        - reference: "Plus"
        - reference: "Slash"
        - reference: "Tilde"
