[package]
name = "codegen_utils"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.66", features = ["std"] }
similar-asserts = "1.4.2"
