[package]
name = "codegen_utils"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
similar-asserts = { workspace = true }
walkdir = { workspace = true }
