[package]
name = "solidity_testing_sanctuary"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
infra_utils = { workspace = true }
indicatif = { workspace = true }
rayon = { workspace = true }
semver = { workspace = true }
slang_solidity = { workspace = true }
solidity_language = { workspace = true }
solidity_testing_utils = { workspace = true }
url = { workspace = true }
