[package]
name = "solidity_testing_sanctuary"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
infra_utils = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slang_solidity = { workspace = true, features = ["__private_ariadne"] }
strum_macros = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
