# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "NumericExpression"
  kind: "Parser"
  versioned:
    0.4.11:
      sequence:
        - choice:
            - reference: "HexLiteral"
            - reference: "DecimalLiteral"
        - optional:
            reference: "NumberUnit"
    0.5.0: # "HexLiteral" no longer allows a "NumberUnit"
      choice:
        - reference: "HexLiteral"
        - sequence:
            - reference: "DecimalLiteral"
            - optional:
                reference: "NumberUnit"

- name: "HexLiteral"
  kind: "Scanner"
  versioned:
    0.4.11:
      sequence:
        - terminal: "0"
        - choice:
            - terminal: "x"
            - terminal: "X"
        - oneOrMore:
            reference: "HexCharacter"
        - zeroOrMore:
            sequence:
              - terminal: "_"
              - oneOrMore:
                  reference: "HexCharacter"
    0.5.0:
      sequence:
        - terminal: "0x"
        - oneOrMore:
            reference: "HexCharacter"
        - zeroOrMore:
            sequence:
              - terminal: "_"
              - oneOrMore:
                  reference: "HexCharacter"

- name: "DecimalLiteral"
  kind: "Scanner"
  versioned:
    0.4.11:
      sequence:
        - choice:
            - sequence:
                - reference: "DecimalNumber"
                - optional:
                    sequence:
                      - terminal: "."
                      - optional:
                          reference: "DecimalNumber"
            - sequence:
                - terminal: "."
                - reference: "DecimalNumber"
        - optional:
            reference: "DecimalExponent"
    0.5.0:
      sequence:
        - choice:
            - sequence:
                - reference: "DecimalNumber"
                - optional:
                    sequence:
                      - terminal: "."
                      - reference: "DecimalNumber"
            - sequence:
                - terminal: "."
                - reference: "DecimalNumber"
        - optional:
            reference: "DecimalExponent"

- name: "DecimalNumber"
  kind: "Scanner"
  unversioned:
    sequence:
      - oneOrMore:
          range:
            from: "0"
            to: "9"
      - zeroOrMore:
          sequence:
            - terminal: "_"
            - oneOrMore:
                range:
                  from: "0"
                  to: "9"

- name: "DecimalExponent"
  kind: "Scanner"
  unversioned:
    sequence:
      - choice:
          - terminal: "e"
          - terminal: "E"
      - optional:
          terminal: "-"
      - reference: "DecimalNumber"

- name: "NumberUnit"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "DaysKeyword"
        - reference: "EtherKeyword"
        - reference: "FinneyKeyword"
        - reference: "HoursKeyword"
        - reference: "MinutesKeyword"
        - reference: "SecondsKeyword"
        - reference: "SzaboKeyword"
        - reference: "WeeksKeyword"
        - reference: "WeiKeyword"
        - reference: "YearsKeyword"
    0.5.0:
      # removed: YearsKeyword
      choice:
        - reference: "DaysKeyword"
        - reference: "EtherKeyword"
        - reference: "FinneyKeyword"
        - reference: "HoursKeyword"
        - reference: "MinutesKeyword"
        - reference: "SecondsKeyword"
        - reference: "SzaboKeyword"
        - reference: "WeeksKeyword"
        - reference: "WeiKeyword"
    0.6.11:
      # added: GweiKeyword
      choice:
        - reference: "DaysKeyword"
        - reference: "EtherKeyword"
        - reference: "FinneyKeyword"
        - reference: "GweiKeyword"
        - reference: "HoursKeyword"
        - reference: "MinutesKeyword"
        - reference: "SecondsKeyword"
        - reference: "SzaboKeyword"
        - reference: "WeeksKeyword"
        - reference: "WeiKeyword"
    0.7.0:
      # removed: SzaboKeyword
      # removed: FinneyKeyword
      choice:
        - reference: "DaysKeyword"
        - reference: "EtherKeyword"
        - reference: "GweiKeyword"
        - reference: "HoursKeyword"
        - reference: "MinutesKeyword"
        - reference: "SecondsKeyword"
        - reference: "WeeksKeyword"
        - reference: "WeiKeyword"
