[package]
name = "ebnf_parser"
version = "0.0.0"
edition = "2021"
rust-version = "1.60.0"

[build-dependencies]
codegen_schema = { path = "../../codegen/schema" }
codegen_utils = { path = "../../codegen/utils" }

[dependencies]
chumsky = "0.8.0"
serde = { version = "1.0.137", features = ["derive", "rc"] }
