[package]
name = "ebnf_parser"
version = "0.0.0"
edition = "2021"
rust-version = "1.60.0"

[build-dependencies]
codegen = { path = "../../codegen" }

[dependencies]
chumsky = "0.8.0"
serde = { version = "1.0.137", features = ["derive", "rc"] }
