# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "TupleDeconstructionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - delimitedBy:
              open:
                reference: "OpenParen"
              expression:
                optional:
                  reference: "TupleMembersList"
              close:
                reference: "CloseParen"
          - reference: "Equal"
          - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "TupleMembersList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      expression:
        reference: "TupleMember"

- name: "TupleMember"
  kind: "Parser"
  unversioned:
    optional:
      choice:
        - sequence:
            - reference: "TypeName"
            - optional:
                reference: "DataLocation"
            - reference: "Identifier"
        - sequence:
            - optional:
                reference: "DataLocation"
            - reference: "Identifier"

- name: "VariableDeclarationStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "VariableDeclaration"
          - optional:
              sequence:
                - reference: "Equal"
                - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "VariableDeclaration"
  kind: "Parser"
  versioned:
    0.4.11:
      sequence:
        - choice:
            - reference: "VarKeyword"
            - reference: "TypeName"
        - optional:
            reference: "DataLocation"
        - reference: "Identifier"
    0.5.0:
      # removed "VarKeyword"
      sequence:
        - reference: "TypeName"
        - optional:
            reference: "DataLocation"
        - reference: "Identifier"

- name: "DataLocation"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "MemoryKeyword"
        - reference: "StorageKeyword"
    0.5.0:
      choice:
        - reference: "MemoryKeyword"
        - reference: "StorageKeyword"
        - reference: "CalldataKeyword"
