# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "TupleDeconstructionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - delimitedBy:
              open:
                reference: "OpenParen"
              parser:
                optional:
                  reference: "TupleMembersList"
              close:
                reference: "CloseParen"
          - reference: "Equal"
          - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "TupleMembersList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "TupleMember"

- name: "TupleMember"
  kind: "Parser"
  unversioned:
    optional:
      choice:
        - sequence:
            - reference: "TypeName"
            - optional:
                reference: "DataLocation"
            - reference: "Identifier"
        - sequence:
            - optional:
                reference: "DataLocation"
            - reference: "Identifier"

- name: "VariableDeclarationStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "VariableDeclarationType"
          - optional:
              reference: "DataLocation"
          - reference: "Identifier"
          - optional:
              sequence:
                - reference: "Equal"
                - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "VariableDeclarationType"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "VarKeyword"
        - reference: "TypeName"
    0.5.0:
      # removed "VarKeyword"
      reference: "TypeName"

- name: "DataLocation"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "MemoryKeyword"
        - reference: "StorageKeyword"
    0.5.0:
      choice:
        - reference: "MemoryKeyword"
        - reference: "StorageKeyword"
        - reference: "CalldataKeyword"
