use itertools::Itertools;
use language_v2_internal_macros::{derive_spanned_type, ParseInputTokens, WriteOutputTokens};
use serde::{Deserialize, Serialize};

use crate::model::{Identifier, VersionSpecifier};

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[derive_spanned_type(Clone, Debug, ParseInputTokens, WriteOutputTokens)]
pub struct KeywordItem {
    pub name: Identifier,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<VersionSpecifier>,

    /// When the keyword is reserved, i.e. can't be used in other position (e.g. as a name)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reserved: Option<VersionSpecifier>,

    /// Underlying keyword scanner (i.e. identifier scanner)
    pub scanner: KeywordScanner,
}

impl KeywordItem {
    pub fn is_unique(&self) -> bool {
        self.scanner.collect_variations().len() == 1
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[derive_spanned_type(Clone, Debug, ParseInputTokens, WriteOutputTokens)]
#[serde(tag = "type")]
pub enum KeywordScanner {
    Sequence { scanners: Vec<KeywordScanner> },
    Optional { scanner: Box<KeywordScanner> },
    Choice { scanners: Vec<KeywordScanner> },
    Atom { atom: String },
}

impl KeywordScanner {
    /// Collects all possible variations generated by this scanner.
    pub fn collect_variations(&self) -> Vec<String> {
        match self {
            KeywordScanner::Atom { atom } => vec![atom.to_owned()],
            KeywordScanner::Optional { scanner } => {
                let mut results = scanner.collect_variations();
                results.insert(0, String::new());
                results
            }
            KeywordScanner::Choice { scanners } => {
                scanners.iter().flat_map(Self::collect_variations).collect()
            }

            KeywordScanner::Sequence { scanners } => {
                let matrix = scanners.iter().map(Self::collect_variations).collect_vec();

                let results_len = matrix.iter().map(Vec::len).product();
                let mut results = (0..results_len).map(|_| String::new()).collect_vec();

                let mut span = results_len;

                for variations in matrix {
                    span /= variations.len();

                    for j in 0..results_len {
                        results[j].push_str(&variations[j / span % variations.len()]);
                    }
                }

                results
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_atom() {
        let scanner = KeywordScanner::Atom { atom: "foo".into() };

        assert_eq!(scanner.collect_variations(), vec!["foo"]);
    }

    #[test]
    fn test_optional() {
        let scanner = KeywordScanner::Optional {
            scanner: KeywordScanner::Atom { atom: "foo".into() }.into(),
        };

        assert_eq!(scanner.collect_variations(), vec!["", "foo"]);
    }

    #[test]
    fn test_choice() {
        let scanner = KeywordScanner::Choice {
            scanners: vec![
                KeywordScanner::Atom { atom: "foo".into() },
                KeywordScanner::Atom { atom: "bar".into() },
            ],
        };

        assert_eq!(scanner.collect_variations(), vec!["foo", "bar"]);
    }

    #[test]
    fn test_sequence() {
        let scanner = KeywordScanner::Sequence {
            scanners: vec![
                KeywordScanner::Atom { atom: "foo".into() },
                KeywordScanner::Atom { atom: "bar".into() },
            ],
        };

        assert_eq!(scanner.collect_variations(), vec!["foobar"]);
    }

    #[test]
    fn test_all() {
        let scanner = KeywordScanner::Sequence {
            scanners: vec![
                KeywordScanner::Atom { atom: "foo".into() },
                KeywordScanner::Optional {
                    scanner: KeywordScanner::Sequence {
                        scanners: vec![
                            KeywordScanner::Atom { atom: "_".into() },
                            KeywordScanner::Choice {
                                scanners: vec![
                                    KeywordScanner::Atom { atom: "1".into() },
                                    KeywordScanner::Atom { atom: "2".into() },
                                    KeywordScanner::Atom { atom: "3".into() },
                                    KeywordScanner::Atom { atom: "4".into() },
                                    KeywordScanner::Atom { atom: "5".into() },
                                ],
                            },
                        ],
                    }
                    .into(),
                },
            ],
        };

        assert_eq!(
            scanner.collect_variations(),
            vec!["foo", "foo_1", "foo_2", "foo_3", "foo_4", "foo_5",]
        );
    }
}
