# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "IdentifierPath"
  kind: "Parser"
  unversioned:
    separatedBy:
      parser:
        reference: "Identifier"
      separator:
        reference: "Period"

- name: "Identifier"
  kind: "Scanner"
  versioned:
    0.4.11:
      difference:
        minuend:
          reference: "RawIdentifier"
        subtrahend:
          choice:
            - reference: "KeywordInAnyVersion"
            - reference: "KeywordInSomeVersion"
            - reference: "ReservedWordInAnyVersion"
    0.5.0:
      # Added "ReservedWordInSomeVersion"
      difference:
        minuend:
          reference: "RawIdentifier"
        subtrahend:
          choice:
            - reference: "KeywordInAnyVersion"
            - reference: "KeywordInSomeVersion"
            - reference: "ReservedWordInAnyVersion"
            - reference: "ReservedWordInSomeVersion"

# TODO: will be removed in https://github.com/NomicFoundation/slang/issues/505
- name: "KeywordInAnyVersion"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      # Types
      - reference: "BytesKeyword"
      - reference: "FixedKeyword"
      - reference: "UfixedKeyword"
      - reference: "IntKeyword"
      - reference: "UintKeyword"
      # Keywords
      - reference: "AddressKeyword"
      - reference: "AnonymousKeyword"
      - reference: "AsKeyword"
      - reference: "AssemblyKeyword"
      - reference: "BoolKeyword"
      - reference: "BreakKeyword"
      - reference: "CaseKeyword"
      - reference: "ConstantKeyword"
      - reference: "ContinueKeyword"
      - reference: "ContractKeyword"
      - reference: "DaysKeyword"
      - reference: "DefaultKeyword"
      - reference: "DeleteKeyword"
      - reference: "DoKeyword"
      - reference: "ElseKeyword"
      - reference: "EnumKeyword"
      - reference: "EtherKeyword"
      - reference: "EventKeyword"
      - reference: "ExternalKeyword"
      - reference: "FalseKeyword"
      - reference: "ForKeyword"
      - reference: "FunctionKeyword"
      - reference: "HoursKeyword"
      - reference: "IfKeyword"
      - reference: "ImportKeyword"
      - reference: "IndexedKeyword"
      - reference: "InterfaceKeyword"
      - reference: "InternalKeyword"
      - reference: "IsKeyword"
      - reference: "LetKeyword"
      - reference: "LibraryKeyword"
      - reference: "MappingKeyword"
      - reference: "MemoryKeyword"
      - reference: "MinutesKeyword"
      - reference: "ModifierKeyword"
      - reference: "NewKeyword"
      - reference: "PayableKeyword"
      - reference: "PragmaKeyword"
      - reference: "PrivateKeyword"
      - reference: "PublicKeyword"
      - reference: "PureKeyword"
      - reference: "ReturnKeyword"
      - reference: "ReturnsKeyword"
      - reference: "SecondsKeyword"
      - reference: "StorageKeyword"
      - reference: "StringKeyword"
      - reference: "StructKeyword"
      - reference: "SwitchKeyword"
      - reference: "TrueKeyword"
      - reference: "UsingKeyword"
      - reference: "ViewKeyword"
      - reference: "WeeksKeyword"
      - reference: "WeiKeyword"
      - reference: "WhileKeyword"

# TODO: will be removed in https://github.com/NomicFoundation/slang/issues/505
- name: "KeywordInSomeVersion"
  kind: "Scanner"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "ByteKeyword"
        - reference: "FinneyKeyword"
        - reference: "SzaboKeyword"
        - reference: "ThrowKeyword"
        - reference: "VarKeyword"
        - reference: "YearsKeyword"
    0.5.0:
      choice:
        # removed:
        # reference: "ThrowKeyword"
        # reference: "VarKeyword"
        # reference: "YearsKeyword"
        # unchanged:
        - reference: "ByteKeyword"
        - reference: "FinneyKeyword"
        - reference: "SzaboKeyword"
        # added:
        - reference: "CalldataKeyword"
        - reference: "ConstructorKeyword"
        - reference: "EmitKeyword"
        - reference: "OverrideKeyword"
    0.5.3:
      choice:
        # unchanged:
        - reference: "ByteKeyword"
        - reference: "FinneyKeyword"
        - reference: "SzaboKeyword"
        - reference: "CalldataKeyword"
        - reference: "ConstructorKeyword"
        - reference: "EmitKeyword"
        - reference: "OverrideKeyword"
        # added:
        - reference: "TypeKeyword"
    0.6.0:
      choice:
        # unchanged:
        - reference: "ByteKeyword"
        - reference: "FinneyKeyword"
        - reference: "SzaboKeyword"
        - reference: "CalldataKeyword"
        - reference: "ConstructorKeyword"
        - reference: "EmitKeyword"
        - reference: "OverrideKeyword"
        - reference: "TypeKeyword"
        # added:
        - reference: "AbstractKeyword"
        - reference: "CatchKeyword"
        - reference: "FallbackKeyword"
        - reference: "ReceiveKeyword"
        - reference: "TryKeyword"
        - reference: "VirtualKeyword"
    0.6.5:
      choice:
        # unchanged:
        - reference: "ByteKeyword"
        - reference: "FinneyKeyword"
        - reference: "SzaboKeyword"
        - reference: "CalldataKeyword"
        - reference: "ConstructorKeyword"
        - reference: "EmitKeyword"
        - reference: "OverrideKeyword"
        - reference: "TypeKeyword"
        - reference: "AbstractKeyword"
        - reference: "CatchKeyword"
        - reference: "FallbackKeyword"
        - reference: "ReceiveKeyword"
        - reference: "TryKeyword"
        - reference: "VirtualKeyword"
        # added:
        - reference: "ImmutableKeyword"
    0.7.0:
      choice:
        # removed:
        # reference: "FinneyKeyword"
        # reference: "SzaboKeyword"
        # unchanged:
        - reference: "ByteKeyword"
        - reference: "CalldataKeyword"
        - reference: "ConstructorKeyword"
        - reference: "EmitKeyword"
        - reference: "OverrideKeyword"
        - reference: "TypeKeyword"
        - reference: "AbstractKeyword"
        - reference: "CatchKeyword"
        - reference: "FallbackKeyword"
        - reference: "ReceiveKeyword"
        - reference: "TryKeyword"
        - reference: "VirtualKeyword"
        - reference: "ImmutableKeyword"
        # added:
        - reference: "GweiKeyword"
    0.8.0:
      choice:
        # removed:
        # reference: "ByteKeyword"
        # unchanged:
        - reference: "CalldataKeyword"
        - reference: "ConstructorKeyword"
        - reference: "EmitKeyword"
        - reference: "OverrideKeyword"
        - reference: "TypeKeyword"
        - reference: "AbstractKeyword"
        - reference: "CatchKeyword"
        - reference: "FallbackKeyword"
        - reference: "ReceiveKeyword"
        - reference: "TryKeyword"
        - reference: "VirtualKeyword"
        - reference: "ImmutableKeyword"
        - reference: "GweiKeyword"
        # added:
        - reference: "UncheckedKeyword"

# TODO: will be removed in https://github.com/NomicFoundation/slang/issues/505
- name: "ReservedWordInAnyVersion"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - terminal: "abstract"
      - terminal: "after"
      - terminal: "byte"
      - terminal: "catch"
      - terminal: "final"
      - terminal: "finney"
      - terminal: "hex"
      - terminal: "in"
      - terminal: "inline"
      - terminal: "match"
      - terminal: "null"
      - terminal: "of"
      - terminal: "relocatable"
      - terminal: "static"
      - terminal: "szabo"
      - terminal: "throw"
      - terminal: "try"
      - terminal: "type"
      - terminal: "typeof"
      - terminal: "var"
      - terminal: "years"

# TODO: will be removed in https://github.com/NomicFoundation/slang/issues/505
- name: "ReservedWordInSomeVersion"
  kind: "Scanner"
  inlined: true
  versioned:
    0.5.0:
      choice:
        - terminal: "alias"
        - terminal: "apply"
        - terminal: "auto"
        - terminal: "copyof"
        - terminal: "define"
        - terminal: "implements"
        - terminal: "macro"
        - terminal: "mutable"
        - terminal: "partial"
        - terminal: "promise"
        - terminal: "reference"
        - terminal: "sealed"
        - terminal: "sizeof"
        - terminal: "supports"
        - terminal: "typedef"

- name: "RawIdentifier"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - reference: "IdentifierStart"
      - zeroOrMore:
          reference: "IdentifierPart"

- name: "IdentifierStart"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - terminal: "_"
      - terminal: "$"
      - range:
          from: "a"
          to: "z"
      - range:
          from: "A"
          to: "Z"

- name: "IdentifierPart"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - reference: "IdentifierStart"
      - range:
          from: "0"
          to: "9"
