# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "EventDefinition"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        sequence:
          - reference: "EventKeyword"
          - reference: "Identifier"
          - reference: "EventParametersDeclaration"
          - optional:
              reference: "AnonymousKeyword"
      terminator:
        reference: "Semicolon"

- name: "EventParametersDeclaration"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      parser:
        optional:
          reference: "EventParameters"
      close:
        reference: "CloseParen"

- name: "EventParameters"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "EventParameter"

- name: "EventParameter"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "TypeName"
      - optional:
          reference: "IndexedKeyword"
      - optional:
          reference: "Identifier"
