# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "InterfaceDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "InterfaceKeyword"
      - reference: "Identifier"
      - optional:
          reference: "InheritanceSpecifier"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            optional:
              reference: "InterfaceMembersList"
          close:
            reference: "CloseBrace"

- name: "InterfaceMembersList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "ContractMember"
