# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "InterfaceDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "InterfaceKeyword"
      - reference: "Identifier"
      - optional:
          reference: "InheritanceSpecifierList"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            zeroOrMore:
              reference: "ContractBodyElement"
          close:
            reference: "CloseBrace"
