[package]
name = "testlang_language"
description = "Testlang language definition compilation"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
codegen_language_definition = { workspace = true }
codegen_language_macros = { workspace = true }
semver = { workspace = true }
