# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ElementaryType"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "BoolKeyword"
        - reference: "ByteKeyword"
        - reference: "StringKeyword"
        - reference: "AddressType"
        - reference: "BytesKeyword"
        - reference: "IntKeyword"
        - reference: "UintKeyword"
        - reference: "FixedKeyword"
        - reference: "UfixedKeyword"
    0.8.0:
      # removed: ByteKeyword
      choice:
        - reference: "BoolKeyword"
        - reference: "StringKeyword"
        - reference: "AddressType"
        - reference: "BytesKeyword"
        - reference: "IntKeyword"
        - reference: "UintKeyword"
        - reference: "FixedKeyword"
        - reference: "UfixedKeyword"

- name: "AddressType"
  kind: "Parser"
  unversioned:
    choice:
      - sequence:
          - reference: "AddressKeyword"
          - optional:
              reference: "PayableKeyword"
      - reference: "PayableKeyword"

- name: "BytesKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        sequence:
          - terminal: "bytes"
          - optional:
              reference: "FixedBytesTypeSize"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FixedBytesTypeSize"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - terminal: "1"
      - terminal: "2"
      - terminal: "3"
      - terminal: "4"
      - terminal: "5"
      - terminal: "6"
      - terminal: "7"
      - terminal: "8"
      - terminal: "9"
      - terminal: "10"
      - terminal: "11"
      - terminal: "12"
      - terminal: "13"
      - terminal: "14"
      - terminal: "15"
      - terminal: "16"
      - terminal: "17"
      - terminal: "18"
      - terminal: "19"
      - terminal: "20"
      - terminal: "21"
      - terminal: "22"
      - terminal: "23"
      - terminal: "24"
      - terminal: "25"
      - terminal: "26"
      - terminal: "27"
      - terminal: "28"
      - terminal: "29"
      - terminal: "30"
      - terminal: "31"
      - terminal: "32"

- name: "IntKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        sequence:
          - terminal: "int"
          - optional:
              reference: "IntegerTypeSize"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "UintKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        sequence:
          - terminal: "uint"
          - optional:
              reference: "IntegerTypeSize"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "IntegerTypeSize"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - terminal: "8"
      - terminal: "16"
      - terminal: "24"
      - terminal: "32"
      - terminal: "40"
      - terminal: "48"
      - terminal: "56"
      - terminal: "64"
      - terminal: "72"
      - terminal: "80"
      - terminal: "88"
      - terminal: "96"
      - terminal: "104"
      - terminal: "112"
      - terminal: "120"
      - terminal: "128"
      - terminal: "136"
      - terminal: "144"
      - terminal: "152"
      - terminal: "160"
      - terminal: "168"
      - terminal: "176"
      - terminal: "184"
      - terminal: "192"
      - terminal: "200"
      - terminal: "208"
      - terminal: "216"
      - terminal: "224"
      - terminal: "232"
      - terminal: "240"
      - terminal: "248"
      - terminal: "256"

- name: "FixedKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        sequence:
          - terminal: "fixed"
          - optional:
              reference: "FixedTypeSize"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "UfixedKeyword"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        sequence:
          - terminal: "ufixed"
          - optional:
              reference: "FixedTypeSize"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "FixedTypeSize"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - oneOrMore:
          range:
            from: "0"
            to: "9"
      - terminal: "x"
      - oneOrMore:
          range:
            from: "0"
            to: "9"
