# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ContractDefinition"
  kind: "Parser"
  versioned:
    0.4.11:
      sequence:
        - reference: "ContractKeyword"
        - reference: "Identifier"
        - optional:
            reference: "InheritanceSpecifier"
        - delimitedBy:
            open:
              reference: "OpenBrace"
            expression:
              optional:
                reference: "ContractMembersList"
            close:
              reference: "CloseBrace"
    0.6.0:
      # added: "AbstractKeyword"
      sequence:
        - optional:
            reference: "AbstractKeyword"
        - reference: "ContractKeyword"
        - reference: "Identifier"
        - optional:
            reference: "InheritanceSpecifier"
        - delimitedBy:
            open:
              reference: "OpenBrace"
            expression:
              optional:
                reference: "ContractMembersList"
            close:
              reference: "CloseBrace"

- name: "InheritanceSpecifier"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IsKeyword"
      - reference: "InheritanceTypesList"

- name: "InheritanceTypesList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      expression:
        reference: "InheritanceType"

- name: "InheritanceType"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IdentifierPath"
      - optional:
          reference: "ArgumentsDeclaration"

- name: "ContractMembersList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "ContractMember"

- name: "ContractMember"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "UsingDirective"
        - reference: "FunctionDefinition"
        - reference: "UnnamedFunctionDefinition"
        - reference: "ModifierDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "EventDefinition"
        - reference: "ErrorDefinition"
        - reference: "StateVariableDefinition"
    0.4.22:
      # added: "ConstructorDefinition"
      choice:
        - reference: "UsingDirective"
        - reference: "ConstructorDefinition"
        - reference: "FunctionDefinition"
        - reference: "UnnamedFunctionDefinition"
        - reference: "ModifierDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "EventDefinition"
        - reference: "ErrorDefinition"
        - reference: "StateVariableDefinition"
    0.6.0:
      # added: "ReceiveFunctionDefinition"
      # added: "FallbackFunctionDefinition"
      # removed: "UnnamedFunctionDefinition"
      choice:
        - reference: "UsingDirective"
        - reference: "ConstructorDefinition"
        - reference: "FunctionDefinition"
        - reference: "FallbackFunctionDefinition"
        - reference: "ReceiveFunctionDefinition"
        - reference: "ModifierDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "EventDefinition"
        - reference: "ErrorDefinition"
        - reference: "StateVariableDefinition"
    0.8.8:
      # added: "UserDefinedValueTypeDefinition"
      choice:
        - reference: "UsingDirective"
        - reference: "ConstructorDefinition"
        - reference: "FunctionDefinition"
        - reference: "FallbackFunctionDefinition"
        - reference: "ReceiveFunctionDefinition"
        - reference: "ModifierDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "EventDefinition"
        - reference: "ErrorDefinition"
        - reference: "StateVariableDefinition"
        - reference: "UserDefinedValueTypeDefinition"
