[package]
name = "codegen_runtime_npm"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

description = "TypeScript runtime copied over by codegen"

[build-dependencies]
anyhow = { workspace = true }
codegen_runtime_generator = { workspace = true }
infra_utils = { workspace = true }
