# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "AssemblyStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AssemblyKeyword"
      - optional:
          reference: "AsciiStringLiteral" # label: "evmasm"
      - optional:
          delimitedBy:
            open:
              reference: "OpenParen"
            parser:
              reference: "AssemblyFlagsList"
            close:
              reference: "CloseParen"
      - reference: "YulBlock"

- name: "AssemblyFlagsList"
  kind: "Parser"
  unversioned:
    separatedBy:
      parser:
        reference: "AsciiStringLiteral"
      separator:
        reference: "Comma"
