# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "AssemblyStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AssemblyKeyword"
      - optional:
          reference: "AsciiStringLiteral" # label: "evmasm"
      - optional:
          reference: "AssemblyFlagsDeclaration"
      - reference: "YulBlock"

- name: "AssemblyFlagsDeclaration"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      parser:
        reference: "AssemblyFlags"
      close:
        reference: "CloseParen"

- name: "AssemblyFlags"
  kind: "Parser"
  unversioned:
    separatedBy:
      parser:
        reference: "AsciiStringLiteral"
      separator:
        reference: "Comma"
