# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "AssemblyStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AssemblyKeyword"
      - optional:
          reference: "Evmasm"
      - optional:
          reference: "AssemblyFlags"
      - reference: "YulBlock"

- name: "Evmasm"
  kind: "Scanner"
  unversioned:
    terminal: '"evmasm"'

- name: "AssemblyFlags"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      expression:
        sequence:
          - reference: "AsciiStringLiteral"
          - zeroOrMore:
              sequence:
                - reference: "Comma"
                - reference: "AsciiStringLiteral"
      close:
        reference: "CloseParen"
