name: "devcontainer/run"

inputs:
  runCmd:
    type: "string"
    required: true

  # TODO: this is a workaround for https://github.com/devcontainers/ci/pull/295
  # Will remove and replace with 'inheritEnv' once the fix is released
  env:
    type: "string"
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Run in devcontainer"
      uses: "devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8"
      with:
        configFile: ".devcontainer/devcontainer.json"
        env: |
          CI
          ${{ inputs.env }}
        push: "never"
        runCmd: "${{ inputs.runCmd }}"
