name: "devcontainer/run"

inputs:
  runCmd:
    type: "string"
    required: true

  env:
    type: "string"
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Run in devcontainer"
      uses: "devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6"
      with:
        configFile: ".devcontainer/devcontainer.json"
        env: |
          CI
          ${{ inputs.env }}
        push: "never"
        runCmd: "${{ inputs.runCmd }}"
