# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "TupleDeconstructionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - delimitedBy:
              open:
                reference: "OpenParen"
              expression:
                optional:
                  separatedBy:
                    separator:
                      reference: "Comma"
                    expression:
                      optional:
                        choice:
                          - sequence:
                              - reference: "TypeName"
                              - optional:
                                  reference: "DataLocation"
                              - reference: "Identifier"
                          - sequence:
                              - optional:
                                  reference: "DataLocation"
                              - reference: "Identifier"
              close:
                reference: "CloseParen"
          - reference: "Equal"
          - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "VariableDeclarationStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "TypeName"
          - optional:
              reference: "DataLocation"
          - reference: "Identifier"
          - optional:
              sequence:
                - reference: "Equal"
                - reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "DataLocation"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "MemoryKeyword"
      - reference: "StorageKeyword"
      - reference: "CalldataKeyword"
