# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "LibraryDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "LibraryKeyword"
      - reference: "Identifier"
      - delimitedBy:
          open: "{"
          expression:
            zeroOrMore:
              reference: "ContractBodyElement"
          close: "}"
