# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "EventDefinition"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "EventKeyword"
          - reference: "Identifier"
          - delimitedBy:
              open:
                reference: "OpenParen"
              expression:
                optional:
                  separatedBy:
                    separator:
                      reference: "Comma"
                    expression:
                      reference: "EventParameter"
              close:
                reference: "CloseParen"
          - optional:
              reference: "AnonymousKeyword"
      terminator:
        reference: "Semicolon"

- name: "EventParameter"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "TypeName"
      - optional:
          reference: "IndexedKeyword"
      - optional:
          reference: "Identifier"
