# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "ImportDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "ImportKeyword"
          - choice:
              - reference: "SimpleImportDirective"
              - reference: "StarImportDirective"
              - reference: "SelectingImportDirective"
      terminator:
        reference: "Semicolon"

- name: "SimpleImportDirective"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ImportPath"
      - zeroOrMore:
          sequence:
            - reference: "AsKeyword"
            - reference: "Identifier"

- name: "StarImportDirective"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Star"
      - reference: "AsKeyword"
      - reference: "Identifier"
      - reference: "FromKeyword"
      - reference: "ImportPath"

- name: "SelectingImportDirective"
  kind: "Parser"
  unversioned:
    sequence:
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            separatedBy:
              separator:
                reference: "Comma"
              expression:
                reference: "SelectedImport"
          close:
            reference: "CloseBrace"
      - reference: "FromKeyword"
      - reference: "ImportPath"

- name: "SelectedImport"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Identifier"
      - optional:
          sequence:
            - reference: "AsKeyword"
            - reference: "Identifier"

- name: "ImportPath"
  kind: "Parser"
  unversioned:
    reference: "AsciiStringLiteral"

- name: "UsingDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "UsingKeyword"
          - choice:
              - reference: "IdentifierPath"
              - delimitedBy:
                  open:
                    reference: "OpenBrace"
                  expression:
                    separatedBy:
                      separator:
                        reference: "Comma"
                      expression:
                        reference: "IdentifierPath"
                  close:
                    reference: "CloseBrace"
          - reference: "ForKeyword"
          - choice:
              - reference: "Star"
              - reference: "TypeName"
          - optional:
              reference: "GlobalKeyword"
      terminator:
        reference: "Semicolon"
