# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "ImportDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "ImportKeyword"
          - choice:
              - reference: "SimpleImportDirective"
              - reference: "StarImportDirective"
              - reference: "SelectingImportDirective"
      terminator:
        reference: "Semicolon"

- name: "SimpleImportDirective"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ImportPath"
      - zeroOrMore:
          sequence:
            - reference: "AsKeyword"
            - reference: "Identifier"

- name: "StarImportDirective"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Star"
      - reference: "AsKeyword"
      - reference: "Identifier"
      - reference: "FromKeyword"
      - reference: "ImportPath"

- name: "SelectingImportDirective"
  kind: "Parser"
  unversioned:
    sequence:
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            separatedBy:
              separator:
                reference: "Comma"
              expression:
                reference: "SelectedImport"
          close:
            reference: "CloseBrace"
      - reference: "FromKeyword"
      - reference: "ImportPath"

- name: "SelectedImport"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Identifier"
      - optional:
          sequence:
            - reference: "AsKeyword"
            - reference: "Identifier"

- name: "ImportPath"
  kind: "Parser"
  unversioned:
    reference: "AsciiStringLiteral"

- name: "UsingDirective"
  kind: "Parser"
  versioned:
    0.4.11:
      terminatedBy:
        expression:
          sequence:
            - reference: "UsingKeyword"
            - choice:
                - reference: "IdentifierPath"
                - delimitedBy:
                    open:
                      reference: "OpenBrace"
                    expression:
                      separatedBy:
                        separator:
                          reference: "Comma"
                        expression:
                          reference: "IdentifierPath"
                    close:
                      reference: "CloseBrace"
            - reference: "ForKeyword"
            - choice:
                - reference: "Star"
                - reference: "TypeName"
            - optional:
                reference: "GlobalKeyword"
        terminator:
          reference: "Semicolon"
    0.8.19:
      # Added "UserDefinedOperator"
      terminatedBy:
        expression:
          sequence:
            - reference: "UsingKeyword"
            - choice:
                - reference: "IdentifierPath"
                - delimitedBy:
                    open:
                      reference: "OpenBrace"
                    expression:
                      separatedBy:
                        separator:
                          reference: "Comma"
                        expression:
                          sequence:
                            - reference: "IdentifierPath"
                            - optional:
                                sequence:
                                  - reference: "AsKeyword"
                                  - reference: "UserDefinedOperator"
                    close:
                      reference: "CloseBrace"
            - reference: "ForKeyword"
            - choice:
                - reference: "Star"
                - reference: "TypeName"
            - optional:
                reference: "GlobalKeyword"
        terminator:
          reference: "Semicolon"

- name: "UserDefinedOperator"
  kind: "Parser"
  versioned:
    0.8.19:
      choice:
        - reference: "Ampersand"
        - reference: "BangEqual"
        - reference: "Bar"
        - reference: "Caret"
        - reference: "EqualEqual"
        - reference: "GreaterThan"
        - reference: "GreaterThanEqual"
        - reference: "LessThan"
        - reference: "LessThanEqual"
        - reference: "Minus"
        - reference: "Percent"
        - reference: "Plus"
        - reference: "Slash"
        - reference: "Star"
        - reference: "Tilde"
