# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "FunctionDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "FunctionKeyword"
      - choice:
          - reference: "Identifier"
          - reference: "FallbackKeyword"
          - reference: "ReceiveKeyword"
      - reference: "ParameterList"
      - zeroOrMore:
          reference: "FunctionAttribute"
      - optional:
          sequence:
            - reference: "ReturnsKeyword"
            - reference: "ParameterList"
      - choice:
          - reference: "Semicolon"
          - reference: "Block"

- name: "FunctionAttribute"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "ConstantKeyword"
        - reference: "ExternalKeyword"
        - reference: "InternalKeyword"
        - reference: "ModifierInvocation"
        - reference: "OverrideSpecifier"
        - reference: "PayableKeyword"
        - reference: "PrivateKeyword"
        - reference: "PublicKeyword"
        - reference: "PureKeyword"
        - reference: "ViewKeyword"
    0.5.0:
      # removed: ConstantKeyword
      choice:
        - reference: "ExternalKeyword"
        - reference: "InternalKeyword"
        - reference: "ModifierInvocation"
        - reference: "OverrideSpecifier"
        - reference: "PayableKeyword"
        - reference: "PrivateKeyword"
        - reference: "PublicKeyword"
        - reference: "PureKeyword"
        - reference: "ViewKeyword"
    0.6.0:
      # added: VirtualKeyword
      choice:
        - reference: "ExternalKeyword"
        - reference: "InternalKeyword"
        - reference: "ModifierInvocation"
        - reference: "OverrideSpecifier"
        - reference: "PayableKeyword"
        - reference: "PrivateKeyword"
        - reference: "PublicKeyword"
        - reference: "PureKeyword"
        - reference: "ViewKeyword"
        - reference: "VirtualKeyword"

- name: "OverrideSpecifier"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "OverrideKeyword"
      - optional:
          delimitedBy:
            open:
              reference: "OpenParen"
            expression:
              separatedBy:
                separator:
                  reference: "Comma"
                expression:
                  reference: "IdentifierPath"
            close:
              reference: "CloseParen"

- name: "ParameterList"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      expression:
        optional:
          separatedBy:
            separator:
              reference: "Comma"
            expression:
              reference: "ParameterDeclaration"
      close:
        reference: "CloseParen"

- name: "ParameterDeclaration"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "TypeName"
      - optional:
          reference: "DataLocation"
      - optional:
          reference: "Identifier"

- name: "ArgumentList"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      expression:
        optional:
          choice:
            - reference: "PositionalArgumentList"
            - reference: "NamedArgumentList"
      close:
        reference: "CloseParen"

- name: "PositionalArgumentList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      expression:
        reference: "Expression"

- name: "NamedArgumentList"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBrace"
      expression:
        optional:
          separatedBy:
            separator:
              reference: "Comma"
            expression:
              reference: "NamedArgument"
      close:
        reference: "CloseBrace"

- name: "FunctionCallOptions"
  kind: "Parser"
  versioned:
    0.4.11:
      oneOrMore:
        delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            optional:
              separatedBy:
                separator:
                  reference: "Comma"
                expression:
                  reference: "NamedArgument"
          close:
            reference: "CloseBrace"
    0.8.0:
      delimitedBy:
        open:
          reference: "OpenBrace"
        expression:
          optional:
            separatedBy:
              separator:
                reference: "Comma"
              expression:
                reference: "NamedArgument"
        close:
          reference: "CloseBrace"

- name: "NamedArgument"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "Identifier"
      - reference: "Colon"
      - reference: "Expression"

- name: "ConstructorDefinition"
  kind: "Parser"
  versioned:
    0.4.22:
      sequence:
        - reference: "ConstructorKeyword"
        - reference: "ParameterList"
        - zeroOrMore:
            reference: "ConstructorAttribute"
        - reference: "Block"

- name: "ConstructorAttribute"
  kind: "Parser"
  versioned:
    0.4.22:
      choice:
        - reference: "ModifierInvocation"
        - reference: "InternalKeyword"
        - reference: "PayableKeyword"
        - reference: "PublicKeyword"

- name: "UnnamedFunctionDefinition"
  kind: "Parser"
  versioned:
    0.4.11:
      sequence:
        - reference: "FunctionKeyword"
        - reference: "ParameterList"
        - zeroOrMore:
            reference: "UnnamedFunctionAttribute"
        - choice:
            - reference: "Semicolon"
            - reference: "Block"
    0.6.0: null

- name: "UnnamedFunctionAttribute"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "ModifierInvocation"
        - reference: "OverrideSpecifier"
        - reference: "ExternalKeyword"
        - reference: "PayableKeyword"
        - reference: "PureKeyword"
        - reference: "ViewKeyword"
    0.6.0: null

- name: "FallbackFunctionDefinition"
  kind: "Parser"
  versioned:
    0.6.0:
      sequence:
        - reference: "FallbackKeyword"
        - reference: "ParameterList"
        - zeroOrMore:
            reference: "FallbackFunctionAttribute"
        - optional:
            sequence:
              - reference: "ReturnsKeyword"
              - reference: "ParameterList"
        - choice:
            - reference: "Semicolon"
            - reference: "Block"

- name: "FallbackFunctionAttribute"
  kind: "Parser"
  versioned:
    0.6.0:
      choice:
        - reference: "ModifierInvocation"
        - reference: "OverrideSpecifier"
        - reference: "ExternalKeyword"
        - reference: "PayableKeyword"
        - reference: "PureKeyword"
        - reference: "ViewKeyword"
        - reference: "VirtualKeyword"

- name: "ReceiveFunctionDefinition"
  kind: "Parser"
  versioned:
    0.6.0:
      sequence:
        - reference: "ReceiveKeyword"
        - reference: "ParameterList"
        - zeroOrMore:
            reference: "ReceiveFunctionAttribute"
        - choice:
            - reference: "Semicolon"
            - reference: "Block"

- name: "ReceiveFunctionAttribute"
  kind: "Parser"
  versioned:
    0.6.0:
      choice:
        - reference: "ModifierInvocation"
        - reference: "OverrideSpecifier"
        - reference: "ExternalKeyword"
        - reference: "PayableKeyword"
        - reference: "VirtualKeyword"
