# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "YulExpression"
  kind: "PrecedenceParser"
  unversioned:
    definitions:
      - name: "YulFunctionCallExpression"
        model: "UnaryPostfix"
        operator:
          delimitedBy:
            open:
              reference: "OpenParen"
            expression:
              optional:
                separatedBy:
                  separator:
                    reference: "Comma"
                  expression:
                    reference: "YulExpression"
            close:
              reference: "CloseParen"

    primaryExpression:
      choice:
        - reference: "YulLiteral"
        - reference: "YulIdentifierPath"

- name: "YulIdentifierPath"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Period"
      expression:
        reference: "YulIdentifier"

- name: "YulIdentifier"
  kind: "Scanner"
  unversioned:
    difference:
      minuend:
        reference: "RawIdentifier"
      subtrahend:
        choice:
          - reference: "YulKeyword"
          - reference: "YulReservedKeyword"

- name: "YulKeyword"
  kind: "Scanner"
  versioned:
    0.4.11:
      choice:
        - reference: "BreakKeyword"
        - reference: "CaseKeyword"
        - reference: "ContinueKeyword"
        - reference: "DefaultKeyword"
        - reference: "FalseKeyword"
        - reference: "ForKeyword"
        - reference: "FunctionKeyword"
        - reference: "IfKeyword"
        - reference: "LetKeyword"
        - reference: "SwitchKeyword"
        - reference: "TrueKeyword"
    0.6.0:
      # added "LeaveKeyword"
      choice:
        - reference: "BreakKeyword"
        - reference: "CaseKeyword"
        - reference: "ContinueKeyword"
        - reference: "DefaultKeyword"
        - reference: "FalseKeyword"
        - reference: "ForKeyword"
        - reference: "FunctionKeyword"
        - reference: "IfKeyword"
        - reference: "LeaveKeyword"
        - reference: "LetKeyword"
        - reference: "SwitchKeyword"
        - reference: "TrueKeyword"

- name: "YulReservedKeyword"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "hex"

- name: "YulLiteral"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "BooleanLiteral"
      - reference: "YulHexLiteral"
      - reference: "YulDecimalLiteral"
      - reference: "HexStringLiteral"
      - reference: "AsciiStringLiteral"

- name: "YulHexLiteral"
  kind: "Scanner"
  unversioned:
    sequence:
      - terminal: "0x"
      - oneOrMore:
          reference: "HexCharacter"

- name: "YulDecimalLiteral"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "0"
      - sequence:
          - range:
              from: "1"
              to: "9"
          - zeroOrMore:
              range:
                from: "0"
                to: "9"
