# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "YulExpressionsList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "YulExpression"

- name: "YulExpression"
  kind: "PrecedenceParser"
  unversioned:
    operatorExpressions:
      - name: "YulFunctionCallExpression"
        model: "UnaryPostfix"
        operator:
          reference: "YulFunctionCallOperator"

    primaryExpression:
      choice:
        - reference: "YulLiteral"
        - reference: "YulIdentifierPath"

- name: "YulFunctionCallOperator"
  kind: "Parser"
  inlined: true
  unversioned:
    delimitedBy:
      open:
        reference: "OpenParen"
      parser:
        optional:
          reference: "YulExpressionsList"
      close:
        reference: "CloseParen"

- name: "YulIdentifierPathsList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "YulIdentifierPath"

- name: "YulIdentifierPath"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Period"
      parser:
        reference: "YulIdentifier"

- name: "YulIdentifiersList"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "YulIdentifier"

- name: "YulIdentifier"
  kind: "Scanner"
  unversioned:
    difference:
      minuend:
        reference: "RawIdentifier"
      subtrahend:
        choice:
          - reference: "YulKeyword"
          - reference: "YulReservedWord"

- name: "YulKeyword"
  kind: "Scanner"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "BreakKeyword"
        - reference: "CaseKeyword"
        - reference: "ContinueKeyword"
        - reference: "DefaultKeyword"
        - reference: "FalseKeyword"
        - reference: "ForKeyword"
        - reference: "FunctionKeyword"
        - reference: "IfKeyword"
        - reference: "LetKeyword"
        - reference: "SwitchKeyword"
        - reference: "TrueKeyword"
    0.6.0:
      # added "LeaveKeyword"
      choice:
        - reference: "BreakKeyword"
        - reference: "CaseKeyword"
        - reference: "ContinueKeyword"
        - reference: "DefaultKeyword"
        - reference: "FalseKeyword"
        - reference: "ForKeyword"
        - reference: "FunctionKeyword"
        - reference: "IfKeyword"
        - reference: "LeaveKeyword"
        - reference: "LetKeyword"
        - reference: "SwitchKeyword"
        - reference: "TrueKeyword"

- name: "YulReservedWord"
  kind: "Scanner"
  inlined: true
  unversioned:
    terminal: "hex"

- name: "YulLiteral"
  kind: "Parser"
  inlined: true
  unversioned:
    choice:
      - reference: "TrueKeyword"
      - reference: "FalseKeyword"
      - reference: "YulHexLiteral"
      - reference: "YulDecimalLiteral"
      - reference: "HexStringLiteral"
      - reference: "AsciiStringLiteral"

- name: "YulHexLiteral"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        sequence:
          - terminal: "0x"
          - oneOrMore:
              reference: "HexCharacter"
      notFollowedBy:
        reference: "IdentifierPart"

- name: "YulDecimalLiteral"
  kind: "Scanner"
  unversioned:
    trailingContext:
      scanner:
        choice:
          - terminal: "0"
          - sequence:
              - range:
                  from: "1"
                  to: "9"
              - zeroOrMore:
                  range:
                    from: "0"
                    to: "9"
      notFollowedBy:
        reference: "IdentifierPart"
