# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "IdentifierPath"
  kind: "Parser"
  unversioned:
    separatedBy:
      expression:
        reference: "Identifier"
      separator:
        reference: "Period"

- name: "Identifier"
  kind: "Scanner"
  unversioned:
    difference:
      minuend:
        reference: "RawIdentifier"
      subtrahend:
        reference: "Keyword"

- name: "Keyword"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "true"
      - terminal: "false"
      - reference: "FixedBytesType"
      - reference: "ReservedKeyword"
      - reference: "SignedIntegerType"
      - reference: "UnsignedIntegerType"
      - terminal: "days"
      - terminal: "ether"
      - terminal: "finney"
      - terminal: "gwei"
      - terminal: "hours"
      - terminal: "minutes"
      - terminal: "seconds"
      - terminal: "szabo"
      - terminal: "weeks"
      - terminal: "wei"
      - terminal: "years"
      - terminal: "abstract"
      - terminal: "address"
      - terminal: "anonymous"
      - terminal: "as"
      - terminal: "assembly"
      - terminal: "bool"
      - terminal: "break"
      - terminal: "calldata"
      - terminal: "catch"
      - terminal: "constant"
      - terminal: "constructor"
      - terminal: "continue"
      - terminal: "contract"
      - terminal: "delete"
      - terminal: "do"
      - terminal: "else"
      - terminal: "emit"
      - terminal: "enum"
      - terminal: "event"
      - terminal: "external"
      - terminal: "fallback"
      - terminal: "false"
      - terminal: "fixed"
      - terminal: "for"
      - terminal: "function"
      - terminal: "hex"
      - terminal: "if"
      - terminal: "immutable"
      - terminal: "import"
      - terminal: "indexed"
      - terminal: "interface"
      - terminal: "internal"
      - terminal: "is"
      - terminal: "library"
      - terminal: "mapping"
      - terminal: "memory"
      - terminal: "modifier"
      - terminal: "new"
      - terminal: "override"
      - terminal: "payable"
      - terminal: "pragma"
      - terminal: "private"
      - terminal: "public"
      - terminal: "pure"
      - terminal: "receive"
      - terminal: "return"
      - terminal: "returns"
      - terminal: "storage"
      - terminal: "string"
      - terminal: "struct"
      - terminal: "true"
      - terminal: "try"
      - terminal: "type"
      - terminal: "ufixed"
      - terminal: "unchecked"
      - terminal: "using"
      - terminal: "view"
      - terminal: "virtual"
      - terminal: "while"

- name: "ReservedKeyword"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "after"
      - terminal: "alias"
      - terminal: "apply"
      - terminal: "auto"
      - terminal: "byte"
      - terminal: "case"
      - terminal: "copyof"
      - terminal: "default"
      - terminal: "define"
      - terminal: "final"
      - terminal: "implements"
      - terminal: "in"
      - terminal: "inline"
      - terminal: "let"
      - terminal: "macro"
      - terminal: "match"
      - terminal: "mutable"
      - terminal: "null"
      - terminal: "of"
      - terminal: "partial"
      - terminal: "promise"
      - terminal: "reference"
      - terminal: "relocatable"
      - terminal: "sealed"
      - terminal: "sizeof"
      - terminal: "static"
      - terminal: "supports"
      - terminal: "switch"
      - terminal: "typedef"
      - terminal: "typeof"
      - terminal: "var"

- name: "RawIdentifier"
  kind: "Scanner"
  unversioned:
    sequence:
      - reference: "IdentifierStart"
      - zeroOrMore:
          reference: "IdentifierPart"

- name: "IdentifierStart"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "_"
      - terminal: "$"
      - range:
          from: "a"
          to: "z"
      - range:
          from: "A"
          to: "Z"

- name: "IdentifierPart"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "IdentifierStart"
      - range:
          from: "0"
          to: "9"
