# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "IdentifierPath"
  kind: "Parser"
  unversioned:
    separatedBy:
      expression:
        reference: "Identifier"
      separator:
        reference: "Period"

- name: "Identifier"
  kind: "Scanner"
  unversioned:
    difference:
      minuend:
        reference: "RawIdentifier"
      subtrahend:
        choice:
          - reference: "Keyword"
          - reference: "ReservedKeyword"
          - reference: "FixedBytesType"
          - reference: "SignedFixedType"
          - reference: "UnsignedFixedType"
          - reference: "SignedIntegerType"
          - reference: "UnsignedIntegerType"

- name: "Keyword"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "AbstractKeyword"
      - reference: "AddressKeyword"
      - reference: "AnonymousKeyword"
      - reference: "AsKeyword"
      - reference: "AssemblyKeyword"
      - reference: "BoolKeyword"
      - reference: "BreakKeyword"
      - reference: "CalldataKeyword"
      - reference: "CaseKeyword"
      - reference: "CatchKeyword"
      - reference: "ConstantKeyword"
      - reference: "ConstructorKeyword"
      - reference: "ContinueKeyword"
      - reference: "ContractKeyword"
      - reference: "DaysKeyword"
      - reference: "DefaultKeyword"
      - reference: "DeleteKeyword"
      - reference: "DoKeyword"
      - reference: "ElseKeyword"
      - reference: "EmitKeyword"
      - reference: "EnumKeyword"
      - reference: "EtherKeyword"
      - reference: "EventKeyword"
      - reference: "ExternalKeyword"
      - reference: "FallbackKeyword"
      - reference: "FalseKeyword"
      - reference: "FinneyKeyword"
      - reference: "ForKeyword"
      - reference: "FunctionKeyword"
      - reference: "GweiKeyword"
      - reference: "HoursKeyword"
      - reference: "IfKeyword"
      - reference: "ImmutableKeyword"
      - reference: "ImportKeyword"
      - reference: "IndexedKeyword"
      - reference: "InterfaceKeyword"
      - reference: "InternalKeyword"
      - reference: "IsKeyword"
      - reference: "LetKeyword"
      - reference: "LibraryKeyword"
      - reference: "MappingKeyword"
      - reference: "MemoryKeyword"
      - reference: "MinutesKeyword"
      - reference: "ModifierKeyword"
      - reference: "NewKeyword"
      - reference: "OverrideKeyword"
      - reference: "PayableKeyword"
      - reference: "PragmaKeyword"
      - reference: "PrivateKeyword"
      - reference: "PublicKeyword"
      - reference: "PureKeyword"
      - reference: "ReceiveKeyword"
      - reference: "ReturnKeyword"
      - reference: "ReturnsKeyword"
      - reference: "SecondsKeyword"
      - reference: "StorageKeyword"
      - reference: "StringKeyword"
      - reference: "StructKeyword"
      - reference: "SwitchKeyword"
      - reference: "SzaboKeyword"
      - reference: "TrueKeyword"
      - reference: "TryKeyword"
      - reference: "TypeKeyword"
      - reference: "UncheckedKeyword"
      - reference: "UsingKeyword"
      - reference: "ViewKeyword"
      - reference: "VirtualKeyword"
      - reference: "WeeksKeyword"
      - reference: "WeiKeyword"
      - reference: "WhileKeyword"
      - reference: "YearsKeyword"

- name: "ReservedKeyword"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "after"
      - terminal: "alias"
      - terminal: "apply"
      - terminal: "auto"
      - terminal: "byte"
      - terminal: "copyof"
      - terminal: "define"
      - terminal: "final"
      - terminal: "hex"
      - terminal: "implements"
      - terminal: "in"
      - terminal: "inline"
      - terminal: "macro"
      - terminal: "match"
      - terminal: "mutable"
      - terminal: "null"
      - terminal: "of"
      - terminal: "partial"
      - terminal: "promise"
      - terminal: "reference"
      - terminal: "relocatable"
      - terminal: "sealed"
      - terminal: "sizeof"
      - terminal: "static"
      - terminal: "supports"
      - terminal: "typedef"
      - terminal: "typeof"
      - terminal: "var"

- name: "RawIdentifier"
  kind: "Scanner"
  unversioned:
    sequence:
      - reference: "IdentifierStart"
      - zeroOrMore:
          reference: "IdentifierPart"

- name: "IdentifierStart"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "_"
      - terminal: "$"
      - range:
          from: "a"
          to: "z"
      - range:
          from: "A"
          to: "Z"

- name: "IdentifierPart"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "IdentifierStart"
      - range:
          from: "0"
          to: "9"
