# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "SourceUnit"
  kind: "Parser"
  unversioned:
    sequence:
      - zeroOrMore:
          choice:
            - reference: "Directive"
            - reference: "Definition"
      - optional:
          reference: "EndOfFileTrivia"

- name: "Directive"
  kind: "Parser"
  unversioned:
    choice:
      - reference: "PragmaDirective"
      - reference: "ImportDirective"
      - reference: "UsingDirective"

- name: "Definition"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "ConstantDefinition"
        - reference: "ContractDefinition"
        - reference: "EnumDefinition"
        - reference: "ErrorDefinition"
        - reference: "FunctionDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
    0.8.8:
      # added: UserDefinedValueTypeDefinition
      choice:
        - reference: "ConstantDefinition"
        - reference: "ContractDefinition"
        - reference: "EnumDefinition"
        - reference: "ErrorDefinition"
        - reference: "FunctionDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "UserDefinedValueTypeDefinition"
