# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "SourceUnit"
  kind: "Parser"
  unversioned:
    sequence:
      - optional:
          reference: "SourceUnitMembers"
      - optional:
          reference: "EndOfFileTrivia"

- name: "SourceUnitMembers"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "SourceUnitMember"

- name: "SourceUnitMember"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
    0.6.0:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        # added"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
    0.7.1:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        # added
        - reference: "FunctionDefinition"
    0.7.4:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "FunctionDefinition"
        # added
        - reference: "ConstantDefinition"
    0.8.4:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "FunctionDefinition"
        - reference: "ConstantDefinition"
        # added:
        - reference: "ErrorDefinition"
    0.8.8:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "FunctionDefinition"
        - reference: "ConstantDefinition"
        - reference: "ErrorDefinition"
        # added:
        - reference: "UserDefinedValueTypeDefinition"
    0.8.13:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "FunctionDefinition"
        - reference: "ConstantDefinition"
        - reference: "ErrorDefinition"
        - reference: "UserDefinedValueTypeDefinition"
        # added:
        - reference: "UsingDirective"
    0.8.22:
      choice:
        - reference: "PragmaDirective"
        - reference: "ImportDirective"
        - reference: "ContractDefinition"
        - reference: "InterfaceDefinition"
        - reference: "LibraryDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "FunctionDefinition"
        - reference: "ConstantDefinition"
        - reference: "ErrorDefinition"
        - reference: "UserDefinedValueTypeDefinition"
        - reference: "UsingDirective"
        # added:
        - reference: "EventDefinition"
