# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "SourceUnit"
  kind: "Parser"
  unversioned:
    sequence:
      - optional:
          reference: "SourceUnitMembersList"
      - optional:
          reference: "EndOfFileTrivia"

- name: "SourceUnitMembersList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "SourceUnitMember"

- name: "SourceUnitMember"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "ContractDefinition"
        - reference: "LibraryDefinition"
        - reference: "InterfaceDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "ConstantDefinition"
        - reference: "FunctionDefinition"
        - reference: "ErrorDefinition"
        - reference: "ImportDirective"
        - reference: "PragmaDirective"
        - reference: "UsingDirective"
    0.8.8:
      choice:
        - reference: "ContractDefinition"
        - reference: "LibraryDefinition"
        - reference: "InterfaceDefinition"
        - reference: "StructDefinition"
        - reference: "EnumDefinition"
        - reference: "ConstantDefinition"
        - reference: "FunctionDefinition"
        - reference: "ErrorDefinition"
        - reference: "ImportDirective"
        - reference: "PragmaDirective"
        - reference: "UsingDirective"
        # added:
        - reference: "UserDefinedValueTypeDefinition"
