# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "ConstantDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "TypeName"
      - reference: "ConstantKeyword"
      - reference: "Identifier"
      - terminal: "="
      - reference: "Expression"
      - terminal: ";"
