# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "Block"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBrace"
      parser:
        optional:
          reference: "StatementsList"
      close:
        reference: "CloseBrace"

- name: "StatementsList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "Statement"

- name: "Statement"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "SimpleStatement"
        - reference: "ControlStatement"
        - reference: "AssemblyStatement"
        - reference: "Block"
    0.8.0:
      choice:
        # added "UncheckedBlock"
        - reference: "SimpleStatement"
        - reference: "ControlStatement"
        - reference: "AssemblyStatement"
        - reference: "Block"
        - reference: "UncheckedBlock"

- name: "ControlStatement"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "DeleteStatement"
        - reference: "ReturnStatement"
        - reference: "ThrowStatement"
    0.4.21:
      choice:
        # added: "EmitStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "DeleteStatement"
        - reference: "ReturnStatement"
        - reference: "ThrowStatement"
        - reference: "EmitStatement"
    0.5.0:
      choice:
        # removed: "ThrowStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "DeleteStatement"
        - reference: "ReturnStatement"
        - reference: "EmitStatement"
    0.6.0:
      choice:
        # added: "TryStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "DeleteStatement"
        - reference: "ReturnStatement"
        - reference: "EmitStatement"
        - reference: "TryStatement"
    0.8.4:
      choice:
        # added: "RevertStatement"
        - reference: "IfStatement"
        - reference: "ForStatement"
        - reference: "WhileStatement"
        - reference: "DoWhileStatement"
        - reference: "ContinueStatement"
        - reference: "BreakStatement"
        - reference: "DeleteStatement"
        - reference: "ReturnStatement"
        - reference: "EmitStatement"
        - reference: "TryStatement"
        - reference: "RevertStatement"

- name: "SimpleStatement"
  kind: "Parser"
  inlined: true
  unversioned:
    choice:
      - reference: "ExpressionStatement"
      - reference: "VariableDeclarationStatement"
      - reference: "TupleDeconstructionStatement"

- name: "ExpressionStatement"
  kind: "Parser"
  unversioned:
    terminatedBy:
      parser:
        reference: "Expression"
      terminator:
        reference: "Semicolon"

- name: "UncheckedBlock"
  kind: "Parser"
  versioned:
    0.8.0:
      sequence:
        - reference: "UncheckedKeyword"
        - reference: "Block"
