# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "LibraryDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "LibraryKeyword"
      - reference: "Identifier"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            optional:
              reference: "LibraryMembersList"
          close:
            reference: "CloseBrace"

- name: "LibraryMembersList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "ContractMember"
