# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "YulBlock"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open:
        reference: "OpenBrace"
      expression:
        zeroOrMore:
          reference: "YulStatement"
      close:
        reference: "CloseBrace"

- name: "YulStatement"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "YulBlock"
        - reference: "YulFunctionDefinition"
        - reference: "YulDeclarationStatement"
        - reference: "YulAssignmentStatement"
        - reference: "YulIfStatement"
        - reference: "YulForStatement"
        - reference: "YulSwitchStatement"
        - reference: "YulBreakStatement"
        - reference: "YulContinueStatement"
        - reference: "YulExpression"
    0.6.0:
      # added "YuiLeaveStatement"
      choice:
        - reference: "YulBlock"
        - reference: "YulFunctionDefinition"
        - reference: "YulDeclarationStatement"
        - reference: "YulAssignmentStatement"
        - reference: "YulIfStatement"
        - reference: "YulForStatement"
        - reference: "YulSwitchStatement"
        - reference: "YulLeaveStatement"
        - reference: "YulBreakStatement"
        - reference: "YulContinueStatement"
        - reference: "YulExpression"

- name: "YulDeclarationStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "LetKeyword"
      - separatedBy:
          separator:
            reference: "Comma"
          expression:
            reference: "YulIdentifierPath"
      - optional:
          sequence:
            - reference: "ColonEqual"
            - reference: "YulExpression"

- name: "YulFunctionDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "FunctionKeyword"
      - reference: "YulIdentifier"
      - delimitedBy:
          open:
            reference: "OpenParen"
          expression:
            optional:
              name: "Arguments"
              separatedBy:
                separator:
                  reference: "Comma"
                expression:
                  reference: "YulIdentifier"
          close:
            reference: "CloseParen"
      - optional:
          sequence:
            - reference: "MinusGreaterThan"
            - name: "Results"
              separatedBy:
                separator:
                  reference: "Comma"
                expression:
                  reference: "YulIdentifier"
      - reference: "YulBlock"

- name: "YulAssignmentStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - separatedBy:
          separator:
            reference: "Comma"
          expression:
            reference: "YulIdentifierPath"
      - reference: "ColonEqual"
      - reference: "YulExpression"

- name: "YulIfStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IfKeyword"
      - reference: "YulExpression"
      - reference: "YulBlock"

- name: "YulLeaveStatement"
  kind: "Parser"
  versioned:
    0.6.0:
      reference: "LeaveKeyword"

- name: "YulBreakStatement"
  kind: "Parser"
  unversioned:
    reference: "BreakKeyword"

- name: "YulContinueStatement"
  kind: "Parser"
  unversioned:
    reference: "ContinueKeyword"

- name: "YulForStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ForKeyword"
      - reference: "YulBlock"
      - reference: "YulExpression"
      - reference: "YulBlock"
      - reference: "YulBlock"

- name: "YulSwitchStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "SwitchKeyword"
      - reference: "YulExpression"
      - oneOrMore:
          sequence:
            - choice:
                - sequence:
                    - reference: "CaseKeyword"
                    - reference: "YulLiteral"
                - reference: "DefaultKeyword"
            - reference: "YulBlock"
