[package]
name = "solidity_testing_utils"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
solidity_rust_lib = { workspace = true }
