[package]
name = "solidity_testing_utils"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
semver = { workspace = true }
slang_solidity = { workspace = true }
