# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "EnumDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "EnumKeyword"
      - reference: "Identifier"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          expression:
            optional:
              separatedBy:
                separator:
                  reference: "Comma"
                expression:
                  reference: "Identifier"
          close:
            reference: "CloseBrace"
