# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "EnumDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "EnumKeyword"
      - reference: "Identifier"
      - delimitedBy:
          open:
            reference: "OpenBrace"
          parser:
            optional:
              reference: "EnumMembers"
          close:
            reference: "CloseBrace"

- name: "EnumMembers"
  kind: "Parser"
  unversioned:
    separatedBy:
      separator:
        reference: "Comma"
      parser:
        reference: "Identifier"
