# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "TypeName"
  kind: "PrecedenceParser"
  unversioned:
    operators:
      - name: "ArrayTypeName"
        model: "UnaryPostfix"
        operator:
          delimitedBy:
            open:
              reference: "OpenBracket"
            expression:
              optional:
                reference: "Expression"
            close:
              reference: "CloseBracket"

    primaryExpression:
      choice:
        - reference: "FunctionType"
        - reference: "MappingType"
        - reference: "ElementaryType"
        - reference: "IdentifierPath"

- name: "FunctionType"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "FunctionKeyword"
      - reference: "ParameterList"
      - zeroOrMore:
          choice:
            - reference: "InternalKeyword"
            - reference: "ExternalKeyword"
            - reference: "PrivateKeyword"
            - reference: "PublicKeyword"
            - reference: "PureKeyword"
            - reference: "ViewKeyword"
            - reference: "PayableKeyword"
      - optional:
          sequence:
            - reference: "ReturnsKeyword"
            - reference: "ParameterList"

- name: "MappingType"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "MappingKeyword"
      - delimitedBy:
          open:
            reference: "OpenParen"
          expression:
            sequence:
              - reference: "MappingKeyType"
              - reference: "EqualGreaterThan"
              - reference: "MappingValueType"
          close:
            reference: "CloseParen"

- name: "MappingKeyType"
  kind: "Parser"
  versioned:
    0.4.11:
      choice:
        - reference: "ElementaryType"
        - reference: "IdentifierPath"
    0.8.18:
      sequence:
        - choice:
            - reference: "ElementaryType"
            - reference: "IdentifierPath"
        - optional:
            reference: "Identifier"

- name: "MappingValueType"
  kind: "Parser"
  versioned:
    0.4.11:
      reference: "TypeName"
    0.8.18:
      sequence:
        - reference: "TypeName"
        - optional:
            reference: "Identifier"
