# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "AssemblyStatement"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AssemblyKeyword"
      - optional:
          terminal: '"evmasm"'
      - optional:
          reference: "AssemblyFlags"
      - reference: "YulBlock"

- name: "AssemblyFlags"
  kind: "Parser"
  unversioned:
    delimitedBy:
      open: "("
      expression:
        separatedBy:
          separator: ","
          expression:
            reference: "DoubleQuotedAsciiStringLiteral"
      close: ")"
