# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "ModifierDefinition"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ModifierKeyword"
      - reference: "Identifier"
      - optional:
          reference: "ParametersDeclaration"
      - optional:
          reference: "ModifierAttributes"
      - choice:
          - reference: "Semicolon"
          - reference: "Block"

- name: "ModifierAttributes"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "ModifierAttribute"

- name: "ModifierAttribute"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      reference: "OverrideSpecifier"
    0.6.0:
      choice:
        - reference: "OverrideSpecifier"
        - reference: "VirtualKeyword"

- name: "ModifierInvocation"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "IdentifierPath"
      - optional:
          reference: "ArgumentsDeclaration"
