# yaml-language-server: $schema=../../../generated/productions.schema.json

- name: "StringExpression"
  kind: "Parser"
  inlined: true
  versioned:
    0.4.11:
      choice:
        - reference: "HexStringLiteralsList"
        - reference: "AsciiStringLiteralsList"
    0.7.0:
      # added "UnicodeStringLiteralsList"
      choice:
        - reference: "HexStringLiteralsList"
        - reference: "AsciiStringLiteralsList"
        - reference: "UnicodeStringLiteralsList"

- name: "HexStringLiteralsList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "HexStringLiteral"

- name: "HexStringLiteral"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "SingleQuotedHexStringLiteral"
      - reference: "DoubleQuotedHexStringLiteral"

- name: "SingleQuotedHexStringLiteral"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: "hex"
      - terminal: "'"
      - optional:
          reference: "HexStringContents"
      - terminal: "'"

- name: "DoubleQuotedHexStringLiteral"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: "hex"
      - terminal: '"'
      - optional:
          reference: "HexStringContents"
      - terminal: '"'

- name: "HexStringContents"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - reference: "HexCharacter"
      - reference: "HexCharacter"
      - zeroOrMore:
          sequence:
            - optional:
                terminal: "_"
            - reference: "HexCharacter"
            - reference: "HexCharacter"

- name: "HexCharacter"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - range:
          from: "0"
          to: "9"
      - range:
          from: "a"
          to: "f"
      - range:
          from: "A"
          to: "F"

- name: "AsciiStringLiteralsList"
  kind: "Parser"
  unversioned:
    oneOrMore:
      reference: "AsciiStringLiteral"

- name: "AsciiStringLiteral"
  kind: "Scanner"
  unversioned:
    choice:
      - reference: "SingleQuotedAsciiStringLiteral"
      - reference: "DoubleQuotedAsciiStringLiteral"

- name: "SingleQuotedAsciiStringLiteral"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: "'"
      - zeroOrMore:
          choice:
            - reference: "EscapeSequence"
            - difference:
                minuend:
                  range:
                    from: " "
                    to: "~"
                subtrahend:
                  choice:
                    - terminal: "'"
                    - terminal: "\\"
      - terminal: "'"

- name: "DoubleQuotedAsciiStringLiteral"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: '"'
      - zeroOrMore:
          choice:
            - reference: "EscapeSequence"
            - difference:
                minuend:
                  range:
                    from: " "
                    to: "~"
                subtrahend:
                  choice:
                    - terminal: '"'
                    - terminal: "\\"
      - terminal: '"'

- name: "UnicodeStringLiteralsList"
  kind: "Parser"
  versioned:
    0.7.0:
      oneOrMore:
        reference: "UnicodeStringLiteral"

- name: "UnicodeStringLiteral"
  kind: "Scanner"
  versioned:
    0.7.0:
      choice:
        - reference: "SingleQuotedUnicodeStringLiteral"
        - reference: "DoubleQuotedUnicodeStringLiteral"

- name: "SingleQuotedUnicodeStringLiteral"
  kind: "Scanner"
  inlined: true
  versioned:
    0.7.0:
      sequence:
        - terminal: "unicode'"
        - zeroOrMore:
            choice:
              - reference: "EscapeSequence"
              - not:
                  choice:
                    - terminal: "'"
                    - terminal: "\\"
                    - terminal: "\n"
                    - terminal: "\r"
        - terminal: "'"

- name: "DoubleQuotedUnicodeStringLiteral"
  kind: "Scanner"
  inlined: true
  versioned:
    0.7.0:
      sequence:
        - terminal: 'unicode"'
        - zeroOrMore:
            choice:
              - reference: "EscapeSequence"
              - not:
                  choice:
                    - terminal: '"'
                    - terminal: "\\"
                    - terminal: "\n"
                    - terminal: "\r"
        - terminal: '"'

- name: "EscapeSequence"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: "\\"
      - choice:
          - reference: "AsciiEscape"
          - reference: "HexByteEscape"
          - reference: "UnicodeEscape"

- name: "AsciiEscape"
  kind: "Scanner"
  inlined: true
  unversioned:
    choice:
      - terminal: "n"
      - terminal: "r"
      - terminal: "t"
      - terminal: "'"
      - terminal: '"'
      - terminal: "\\"
      - terminal: "\n"
      - terminal: "\r"

- name: "HexByteEscape"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: "x"
      - reference: "HexCharacter"
      - reference: "HexCharacter"

- name: "UnicodeEscape"
  kind: "Scanner"
  inlined: true
  unversioned:
    sequence:
      - terminal: "u"
      - reference: "HexCharacter"
      - reference: "HexCharacter"
      - reference: "HexCharacter"
      - reference: "HexCharacter"
