site_name: Slang

repo_url: https://github.com/NomicFoundation/slang
repo_name: NomicFoundation/slang
edit_uri: blob/main/documentation/docs/

docs_dir: !ENV DOCS_DIR
site_dir: !ENV SITE_DIR

nav:
  - Home: index.md
  - "": snippets/under-construction.md
  - Language Reference:
      - 1. File Structure:
          - 1.1. License Specifier: reference/01-file-structure/01-license-specifier/index.md
          - 1.2. Pragmas: reference/01-file-structure/02-pragmas/index.md
          - 1.3. Imports: reference/01-file-structure/03-imports/index.md
          - 1.4. Comments: reference/01-file-structure/04-comments/index.md
          - 1.5. NatSpec Format: reference/01-file-structure/05-natspec-format/index.md
      - 2. Contracts:
          - 2.1. State Variables: reference/02-contracts/01-state-variables/index.md
          - 2.2. Functions: reference/02-contracts/02-functions/index.md
          - 2.3. Events: reference/02-contracts/03-events/index.md
          - 2.4. Errors: reference/02-contracts/04-errors/index.md
      - 3. Primitives:
          - 3.1. Booleans: reference/03-primitives/01-booleans/index.md
          - 3.2. Numbers: reference/03-primitives/02-numbers/index.md
          - 3.3. Strings: reference/03-primitives/03-strings/index.md
          - 3.4. Addresses: reference/03-primitives/04-addresses/index.md
      - 4. Advanced Types:
          - 4.1. Enums: reference/04-advanced-types/01-enums/index.md
          - 4.2. Structs: reference/04-advanced-types/02-structs/index.md
          - 4.3. Arrays: reference/04-advanced-types/03-arrays/index.md
          - 4.4. Mapping Types: reference/04-advanced-types/04-mapping-types/index.md
          - 4.5. User Defined Value Types: reference/04-advanced-types/05-user-defined-value-types/index.md
          - 4.6. Function Types: reference/04-advanced-types/06-function-types/index.md
      - 5. Expressions:
          - 5.1. Operators: reference/05-expressions/01-operators/index.md
