site_name: Slang

repo_url: https://github.com/NomicFoundation/slang
repo_name: NomicFoundation/slang
edit_uri: blob/main/documentation/docs/

docs_dir: !ENV DOCUMENTATION_SOURCE_FILES
site_dir: !ENV DOCUMENTATION_SITE_DIR

nav:
  - Home: index.md
  - "": snippets/under-construction.md
