site_name: "Slang"

repo_url: "https://github.com/NomicFoundation/slang"
repo_name: "NomicFoundation/slang"
edit_uri: "blob/main/documentation/docs/"

docs_dir: !ENV "DOCUMENTATION_SOURCE_FILES"
site_dir: !ENV "DOCUMENTATION_SITE_DIR"

nav:
  - "index.md"
  - Internals:
      - Code Generation:
          - "internals/01-code-generation/01-syntax-schema/index.md"
          - "internals/01-code-generation/02-parser/index.md"
          - "internals/01-code-generation/03-syntax-tree/index.md"
