name: "jobs/sanctuary"

on:
  # Run when invoked from other workflows:
  workflow_call:
    inputs:
      chain:
        description: "Name of the chain/sanctuary to run against, e.g. 'ethereum' or 'tron'."
        required: true
        type: "string"
      network:
        description: "Name of the sub-network to run against, e.g. 'mainnet' or 'testnet'."
        required: true
        type: "string"

jobs:
  sanctuary:
    runs-on: "ubuntu-22.04" # _SLANG_DEV_CONTAINER_BASE_IMAGE_ (keep in sync)

    strategy:
      fail-fast: false # Continue running all shards even if some fail.
      matrix:
        shard_index:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15

    env:
      SHARDS_COUNT: 16 # Length of the 'shard_index' array above.

    steps:
      #
      # _DEVCONTAINER_PREPARATION_STEPS_ (keep in sync)
      # Cache is updated in the "ci" workflow, then reused here.
      #

      - name: "Clone repository"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332"

      - name: "Restore CI cache"
        uses: "actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9"
        with:
          key: "cache-${{ github.ref_name }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('package-lock.json') }}"
          restore-keys: |
            cache-${{ github.ref_name }}-
            cache-main-
            cache-
          path: |
            ~/.cache/hermit/
            ~/.local/share/virtualenvs/
            .hermit/

      #
      # Run Sanctuary Tests:
      #

      - run: "scripts/bin/infra setup cargo"

      - run: |
          scripts/bin/infra run --release --bin "solidity_testing_sanctuary" -- \
            --shards-count ${{ env.SHARDS_COUNT }} \
            --shard-index ${{ matrix.shard_index }} \
            "${{ inputs.chain }}" "${{ inputs.network }}"
