name: "benchmark"

on:
  # Run using manual triggers from GitHub UI:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Attempt a local run and report results here, without updating the bencher dashboard."
        type: "boolean"
        required: true
        default: true
      runCargo:
        description: "Runs the cargo benchmarks."
        type: "boolean"
        required: true
        default: true

      runNPM:
        description: "Runs the npm benchmarks."
        type: "boolean"
        required: true
        default: true

  # Run on pushes to 'main' branch:
  push:
    branches:
      - "main"

# Queue up benchmark workflows for the same branch, so that results are reported in order:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: false

jobs:
  benchmark:
    runs-on: "ubuntu-22.04" # _SLANG_DEV_CONTAINER_BASE_IMAGE_ (keep in sync)

    # Only run on the main repo (not forks), unless it is a dry run:
    if: "${{ github.repository == 'NomicFoundation/slang' || github.event.inputs.dryRun == true }}"

    steps:
      # Installs basic dependencies when running locally with https://github.com/nextos/act,
      # whose Ubuntu image is bare
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo curl build-essential git pkg-config libssl-dev -y

      - name: "Checkout Repository"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: "Restore Cache"
        uses: "./.github/actions/cache/restore"

      - name: "infra setup"
        run: "./scripts/bin/infra setup"

      - name: "infra perf fetch"
        run: "./scripts/bin/infra perf fetch"

      - name: "infra perf cargo"
        run: "echo './scripts/bin/infra perf cargo ${{ github.event.inputs.dryRun == true && '--dry-run' || '' }}'"
        env:
          BENCHER_API_TOKEN: "${{ secrets.BENCHER_API_TOKEN }}"
        if: "${{ github.event.inputs.runCargo }}"

      - name: "infra check"
        run: "echo './scripts/bin/infra check'"
        if: "${{ github.event.inputs.runNPM }}"

      - name: "infra perf npm"
        run: "echo './scripts/bin/infra perf npm ${{ github.event.inputs.dryRun == true && '--dry-run' || '' }}'"
        env:
          BENCHER_API_TOKEN: "${{ secrets.BENCHER_API_TOKEN }}"
        if: "${{ github.event.inputs.runNPM }}"

      - name: "Upload Benchmarking Data"
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
        with:
          name: "benchmarking-data"
          path: "target/iai"
          if-no-files-found: "error"
        if: "${{ github.event.inputs.runCargo }}"
