name: "sourcify_all_chains"

on:
  workflow_dispatch:
    inputs:
      check_binder_v1:
        description: "Check name bindings on contracts using the graph binder, reporting if there's any unresolved symbol. Only one binder check can be enabled."
        type: "boolean"
        required: false
        default: false
      check_binder_v2:
        description: "Check name bindings on contracts using the new binder, reporting if there's any unresolved symbol. Only one binder check can be enabled."
        type: "boolean"
        required: false
        default: false
      compare_binders:
        description: "Check bindings using the new binder and compare the results against the graph binder, reporting any differences found as failures. Only one binder check can be enabled."
        type: "boolean"
        required: false
        default: false
      check_infer_version:
        description: "Check that we can infer the correct language version based on the available version pragmas."
        type: "boolean"
        required: false
        default: false
jobs:
  run_tests:
    uses: "./.github/workflows/sourcify_single_chain.yml"
    with:
      chain_id: "${{ matrix.chain_id }}"
      check_binder_v1: "${{ inputs.check_binder_v1 }}"
      check_binder_v2: "${{ inputs.check_binder_v2 }}"
      compare_binders: "${{ inputs.compare_binders }}"
      check_infer_version: "${{ inputs.check_infer_version }}"
    strategy:
      fail-fast: false
      matrix:
        chain_id:
          - 1 # Ethereum Mainnet
          - 42161 # Arbitrum One
          - 8453 # Base
          - 137 # Polygon Mainnet
