name: "sourcify_smoke"

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopened"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"

jobs:
  smoke:
    runs-on: "ubuntu-24.04" # _SLANG_DEV_CONTAINER_BASE_IMAGE_ (keep in sync)

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          persist-credentials: false
          fetch-depth: 0 # Full history is needed by 'chetan/git-restore-mtime-action' to find each file's last commit time.

      - name: "Restore Cache"
        uses: "./.github/actions/cache/restore"

      - name: "Smoke Test > Build sourcify binary"
        run: "./scripts/bin/with-hermit cargo build --bin solidity_testing_sourcify"
