name: "sourcify_all_chains"

on:
  pull_request:
  workflow_dispatch:
    inputs:
      check_bindings:
        description: "Check name bindings on contracts, failing if there's any unresolved symbol."
        type: "boolean"
        required: false
        default: false
      check_infer_version:
        description: "Check that we can infer the correct language version based on the available version pragmas."
        type: "boolean"
        required: false
        default: false
jobs:
  run_tests:
    uses: "./.github/workflows/sourcify_single_chain.yml"
    with:
      chain_id: "${{ matrix.chain_id }}"
      check_bindings: "${{ inputs.check_bindings || false }}"
      check_infer_version: "${{ inputs.check_infer_version || true }}"
    strategy:
      fail-fast: false
      matrix:
        chain_id:
          - 1 # Ethereum Mainnet
          - 42161 # Arbitrum One
          - 8453 # Base
          - 137 # Polygon Mainnet
