[package]
name = "solidity_testing_perf_npmdriver"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
infra_utils = { workspace = true }
anyhow = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
