# yaml-language-server: $schema=../../../../../../../codegen/schema/generated/productions.schema.json

- name: "PragmaDirective"
  kind: "Parser"
  unversioned:
    terminatedBy:
      expression:
        sequence:
          - reference: "PragmaKeyword"
          - choice:
              - reference: "VersionPragma"
              - reference: "ABICoderPragma"
              - reference: "ExperimentalPragma"
      terminator:
        reference: "Semicolon"

- name: "VersionPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "SolidityKeyword"
      - oneOrMore:
          reference: "VersionPragmaSpecifier"

- name: "VersionPragmaSpecifier"
  kind: "Parser"
  unversioned:
    sequence:
      - optional:
          reference: "VersionPragmaOperator"
      - separatedBy:
          separator:
            reference: "Period"
          expression:
            reference: "VersionPragmaValue"

- name: "VersionPragmaOperator"
  kind: "Scanner"
  unversioned:
    choice:
      - terminal: "^"
      - terminal: "~"
      - terminal: "="
      - terminal: "<"
      - terminal: ">"
      - terminal: "<="
      - terminal: ">="

- name: "VersionPragmaValue"
  kind: "Scanner"
  unversioned:
    oneOrMore:
      choice:
        - range:
            from: "0"
            to: "9"
        - terminal: "x"
        - terminal: "X"
        - terminal: "*"

- name: "ABICoderPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "AbicoderKeyword"
      - reference: "Identifier"

- name: "ExperimentalPragma"
  kind: "Parser"
  unversioned:
    sequence:
      - reference: "ExperimentalKeyword"
      - reference: "Identifier"
